//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;

    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    //[SdmDomMapper]
    internal static class AssetManagerAppSettingsDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.SlcAsset_Management.ModuleId;
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(SharedMappers.DomIds.SlcAsset_Management.Definitions.AssetManagerAppSettings.Id)
        { ModuleId = ModuleId };
        internal static class AppSettings
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AppSettings.Id.Id)
            { ModuleId = ModuleId };
            internal static FieldDescriptorID EnableAssetHistory = SharedMappers.DomIds.SlcAsset_Management.Sections.AppSettings.EnableAssetHistory;
            internal static FieldDescriptorID PlanAndBuildJobPrompt = SharedMappers.DomIds.SlcAsset_Management.Sections.AppSettings.PlanAndBuildJobPrompt;
            internal static FieldDescriptorID EnableConnectionHistory = SharedMappers.DomIds.SlcAsset_Management.Sections.AppSettings.EnableConnectionHistory;
            internal static FieldDescriptorID HistoryTTL = SharedMappers.DomIds.SlcAsset_Management.Sections.AppSettings.HistoryTTL;
            internal static FieldDescriptorID HistoryLimit = SharedMappers.DomIds.SlcAsset_Management.Sections.AppSettings.HistoryLimit;
        }
    }
}
