//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;

    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    //[SdmDomMapper]
    internal static class AssetDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.SlcAsset_Management.ModuleId;
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(SharedMappers.DomIds.SlcAsset_Management.Definitions.Asset.Id)
        { ModuleId = ModuleId };
        internal static class AssetProperties
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID AssetId = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.AssetID;
            internal static FieldDescriptorID AssetName = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.AssetName;
            internal static FieldDescriptorID AssetClass = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.AssetClass;
            internal static FieldDescriptorID AssetDescription = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.AssetDescription;
            internal static FieldDescriptorID FwOs = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.FWOS;
            internal static FieldDescriptorID SerialNumber = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.SerialNumber;
            internal static FieldDescriptorID HardwareVersion = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.HardwareVersion;
            internal static FieldDescriptorID OperationalFlags = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetInformation.OperationalFlags;
        }

        internal static class NetworkDetails
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetNetworkDetails.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID MACAddress = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetNetworkDetails.MACAddress;

        }

        internal static class Location
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID HolderNumber = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.HolderNumber;
            internal static FieldDescriptorID ParentAsset = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.ParentAsset;
            internal static FieldDescriptorID Rack = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.Rack;
            internal static FieldDescriptorID RackPosition = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.RackPosition;
            internal static FieldDescriptorID Side = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.Side;
            internal static FieldDescriptorID Desk = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.Desk;
            internal static FieldDescriptorID Container = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.Container;
            internal static FieldDescriptorID Room = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.Room;
            internal static FieldDescriptorID PowerSupplyRackPosition = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocation.PowerSupplyRackPosition;
        }

        internal static class DestinationLocation
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID HolderNumber = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.HolderNumber;
            internal static FieldDescriptorID ParentAsset = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.ParentAsset;
            internal static FieldDescriptorID Rack = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.Rack;
            internal static FieldDescriptorID RackPosition = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.RackPosition;
            internal static FieldDescriptorID Side = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.Side;
            internal static FieldDescriptorID Desk = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.Desk;
            internal static FieldDescriptorID Container = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.Container;
            internal static FieldDescriptorID Room = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.Room;
            internal static FieldDescriptorID PowerSupplyRackPosition = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLocationDestination.PowerSupplyRackPosition;
        }

        internal static class Lifecycle
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID PurchaseDate = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.PurchaseDate;
            internal static FieldDescriptorID FirstUseDate = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.FirstUseDate;
            internal static FieldDescriptorID EndOfWarrantyDate = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.EndOfWarrantyDate;
            internal static FieldDescriptorID InstallationDate = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.InstallationDate;
            internal static FieldDescriptorID InstallationUser = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.InstallationUser;
            internal static FieldDescriptorID ModificationDate = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.ModificationDate;
            internal static FieldDescriptorID ModificationUser = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.ModificationUser;
            internal static FieldDescriptorID EndOfLife = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetLifecycle.EndOfLife;
        }

        internal static class Ownership
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetOwnership.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID Organization = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetOwnership.Organization;
            internal static FieldDescriptorID ContactPerson = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetOwnership.ContactPerson;
            internal static FieldDescriptorID ContactPersonRole = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetOwnership.ContactPersonRole;
            internal static FieldDescriptorID Team = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetOwnership.Team;
        }

        internal static class Custody
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID From = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.From;
            internal static FieldDescriptorID Till = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.Till;
            internal static FieldDescriptorID ContactPerson = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.ContactPerson;
            internal static FieldDescriptorID Team = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.Team;
            internal static FieldDescriptorID Organization = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.Organization;
            internal static FieldDescriptorID ContactPersonRole = SharedMappers.DomIds.SlcAsset_Management.Sections.AssetCustody.ContactPersonRole;
        }

        internal static class Holders
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.Holders.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID SlotNumber = SharedMappers.DomIds.SlcAsset_Management.Sections.Holders.SlotNumber;
            internal static FieldDescriptorID HierarchyRole = SharedMappers.DomIds.SlcAsset_Management.Sections.Holders.HierarchyRole;


        }

        internal static class ElementLinks
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.ElementLink.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID ElementID = SharedMappers.DomIds.SlcAsset_Management.Sections.ElementLink.ElementID;
            internal static FieldDescriptorID IsPrimary = SharedMappers.DomIds.SlcAsset_Management.Sections.ElementLink.IsPrimary;
        }
    }
}