//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    //[SdmDomMapper]
    public static class CableTypeDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.SlcAsset_Management.ModuleId;
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(SharedMappers.DomIds.SlcAsset_Management.Definitions.CableType.Id)
        {ModuleId = ModuleId};
        internal static class CableTypeProperties
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.CableTypeInformation.Id.Id)
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Name = SharedMappers.DomIds.SlcAsset_Management.Sections.CableTypeInformation.Name;
            internal static FieldDescriptorID Description = SharedMappers.DomIds.SlcAsset_Management.Sections.CableTypeInformation.Description;
        }

        internal static class CategoryRelation
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcAsset_Management.Sections.CategoryLink.Id.Id)
            {ModuleId = ModuleId};
            internal static FieldDescriptorID CategoryLinks = SharedMappers.DomIds.SlcAsset_Management.Sections.CategoryLink.Categories;
        }
    }
}