//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGen package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.InfraOpsProperties.Models
{
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.InfraOpsProperties.Models;

    using SLDataGateway.API.Types.Querying;

    using System;
    using System.Collections.Generic;

    internal sealed partial class PropertyValuesDomRepository_Middleware : IBulkRepository<InfraOpsProperties.Models.PropertyValues>
    {
        private readonly IBulkRepository<InfraOpsProperties.Models.PropertyValues> _inner;
        private readonly IMiddlewareMarker<InfraOpsProperties.Models.PropertyValues> _middleware;

        public PropertyValuesDomRepository_Middleware(IBulkRepository<InfraOpsProperties.Models.PropertyValues> inner, IMiddlewareMarker<InfraOpsProperties.Models.PropertyValues> middleware)
        {
            _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            _middleware = middleware;
        }

        public IEnumerable<IPagedResult<InfraOpsProperties.Models.PropertyValues>> ReadPaged(FilterElement<InfraOpsProperties.Models.PropertyValues> filter)
        {
            if (_middleware is IPageableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnReadPaged(filter, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter);
            }
        }

        public IEnumerable<IPagedResult<InfraOpsProperties.Models.PropertyValues>> ReadPaged(IQuery<InfraOpsProperties.Models.PropertyValues> query)
        {
            if (_middleware is IPageableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnReadPaged(query, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query);
            }
        }

        public IEnumerable<IPagedResult<InfraOpsProperties.Models.PropertyValues>> ReadPaged(FilterElement<InfraOpsProperties.Models.PropertyValues> filter, int pageSize)
        {
            if (_middleware is IPageableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter, pageSize);
            }
        }

        public IEnumerable<IPagedResult<InfraOpsProperties.Models.PropertyValues>> ReadPaged(IQuery<InfraOpsProperties.Models.PropertyValues> query, int pageSize)
        {
            if (_middleware is IPageableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query, pageSize);
            }
        }

        public IEnumerable<InfraOpsProperties.Models.PropertyValues> Read(FilterElement<InfraOpsProperties.Models.PropertyValues> filter)
        {
            if (_middleware is IReadableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnRead(filter, _inner.Read);
            }
            else
            {
                return _inner.Read(filter);
            }
        }

        public IEnumerable<InfraOpsProperties.Models.PropertyValues> Read(IQuery<InfraOpsProperties.Models.PropertyValues> query)
        {
            if (_middleware is IReadableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnRead(query, _inner.Read);
            }
            else
            {
                return _inner.Read(query);
            }
        }

        public long Count(FilterElement<InfraOpsProperties.Models.PropertyValues> filter)
        {
            if (_middleware is ICountableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnCount(filter, _inner.Count);
            }
            else
            {
                return _inner.Count(filter);
            }
        }

        public long Count(IQuery<InfraOpsProperties.Models.PropertyValues> query)
        {
            if (_middleware is ICountableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnCount(query, _inner.Count);
            }
            else
            {
                return _inner.Count(query);
            }
        }

        public IReadOnlyCollection<InfraOpsProperties.Models.PropertyValues> Create(IEnumerable<InfraOpsProperties.Models.PropertyValues> oToCreate)
        {
            if (_middleware is IBulkCreatableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public InfraOpsProperties.Models.PropertyValues Create(InfraOpsProperties.Models.PropertyValues oToCreate)
        {
            if (_middleware is ICreatableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public IReadOnlyCollection<InfraOpsProperties.Models.PropertyValues> Update(IEnumerable<InfraOpsProperties.Models.PropertyValues> oToUpdate)
        {
            if (_middleware is IBulkUpdatableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public InfraOpsProperties.Models.PropertyValues Update(InfraOpsProperties.Models.PropertyValues oToUpdate)
        {
            if (_middleware is IUpdatableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public void Delete(IEnumerable<InfraOpsProperties.Models.PropertyValues> oToDelete)
        {
            if (_middleware is IBulkDeletableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }

        public void Delete(InfraOpsProperties.Models.PropertyValues oToDelete)
        {
            if (_middleware is IDeletableMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }
        public System.Collections.Generic.IReadOnlyCollection<InfraOpsProperties.Models.PropertyValues> CreateOrUpdate(System.Collections.Generic.IEnumerable<InfraOpsProperties.Models.PropertyValues> oToCreateOrUpdate)
        {
                if (_middleware is IBulkRepositoryMiddleware<InfraOpsProperties.Models.PropertyValues> middleware)
                {
                    return middleware.OnCreateOrUpdate(oToCreateOrUpdate, _inner.CreateOrUpdate);
                }
                else
                {
                    return _inner.CreateOrUpdate(oToCreateOrUpdate);
                }
        }

    }
}
