//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Skyline.DataMiner.Net;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Apps.Sections.Sections;
    using Skyline.DataMiner.Net.Helper;
    using Skyline.DataMiner.Net.ManagerStore;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Net.SubscriptionFilters;
    using Skyline.DataMiner.SDM;

    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    internal sealed partial class CableTypeDomRepository_Middleware : Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.AssetManagement.Models.CableType>
    {
        private readonly Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> _inner;
        private readonly IMiddlewareMarker<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> _middleware;

        public CableTypeDomRepository_Middleware(Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> inner, IMiddlewareMarker<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
        {
            _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            _middleware = middleware;
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.AssetManagement.Models.CableType>> ReadPaged(FilterElement<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> filter)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnReadPaged(filter, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.AssetManagement.Models.CableType>> ReadPaged(IQuery<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> query)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnReadPaged(query, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.AssetManagement.Models.CableType>> ReadPaged(FilterElement<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> filter, int pageSize)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter, pageSize);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.AssetManagement.Models.CableType>> ReadPaged(IQuery<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> query, int pageSize)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query, pageSize);
            }
        }

        public IEnumerable<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> Read(FilterElement<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> filter)
        {
            if (_middleware is IReadableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnRead(filter, _inner.Read);
            }
            else
            {
                return _inner.Read(filter);
            }
        }

        public IEnumerable<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> Read(IQuery<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> query)
        {
            if (_middleware is IReadableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnRead(query, _inner.Read);
            }
            else
            {
                return _inner.Read(query);
            }
        }

        public long Count(FilterElement<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> filter)
        {
            if (_middleware is ICountableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnCount(filter, _inner.Count);
            }
            else
            {
                return _inner.Count(filter);
            }
        }

        public long Count(IQuery<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> query)
        {
            if (_middleware is ICountableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnCount(query, _inner.Count);
            }
            else
            {
                return _inner.Count(query);
            }
        }

        public IReadOnlyCollection<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> Create(IEnumerable<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> oToCreate)
        {
            if (_middleware is IBulkCreatableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public Skyline.DataMiner.SDM.AssetManagement.Models.CableType Create(Skyline.DataMiner.SDM.AssetManagement.Models.CableType oToCreate)
        {
            if (_middleware is ICreatableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public IReadOnlyCollection<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> Update(IEnumerable<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> oToUpdate)
        {
            if (_middleware is IBulkUpdatableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public Skyline.DataMiner.SDM.AssetManagement.Models.CableType Update(Skyline.DataMiner.SDM.AssetManagement.Models.CableType oToUpdate)
        {
            if (_middleware is IUpdatableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public void Delete(IEnumerable<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> oToDelete)
        {
            if (_middleware is IBulkDeletableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }

        public void Delete(Skyline.DataMiner.SDM.AssetManagement.Models.CableType oToDelete)
        {
            if (_middleware is IDeletableMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }
        public System.Collections.Generic.IReadOnlyCollection<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> CreateOrUpdate(System.Collections.Generic.IEnumerable<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> oToCreateOrUpdate)
        {
                if (_middleware is IBulkRepositoryMiddleware<Skyline.DataMiner.SDM.AssetManagement.Models.CableType> middleware)
                {
                    return middleware.OnCreateOrUpdate(oToCreateOrUpdate, _inner.CreateOrUpdate);
                }
                else
                {
                    return _inner.CreateOrUpdate(oToCreateOrUpdate);
                }
        }

    }
}
