//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
	using System;
	using System.Collections.Generic;
	using System.Diagnostics;
	using System.Linq;

	using Skyline.DataMiner.Net;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.Net.SubscriptionFilters;
	using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.AssetManagement.Repositories;
    using Skyline.DataMiner.SDM.AssetManagement.Validation;

    using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;
    using SharedMappers.DomIds;

	internal partial class AssetClassDomRepository : IBulkRepository<AssetClass>, IAssetClassQueryRepository
    {
		private readonly IConnection connection;
		private readonly DomHelper helper;

        public AssetClassDomRepository(IConnection connection)
		{
			this.connection = connection;
			this.helper = new DomHelper(connection.HandleMessages, Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.ModuleId);
		}

        public AssetClass Create(AssetClass createObject)
		{
			if (createObject is null)
			{
				throw new ArgumentNullException(nameof(createObject));
			}

			var instance = ToInstance(createObject);
			instance = helper.DomInstances.Create(instance);
			return FromInstance(instance);
		}

        public IReadOnlyCollection<AssetClass> Create(IEnumerable<AssetClass> createObjects)
        {
            if (createObjects is null || !createObjects.Any())
            {
                return Array.Empty<AssetClass>();
            }

            // Check if some of the objects already exist
            // Only check objects that have an Identifier (new objects with empty identifiers can't exist yet)
            var existing = new HashSet<string>();
            var objectsWithIdentifier = createObjects.Where(obj => !string.IsNullOrWhiteSpace(obj.Identifier)).ToList();

            if (objectsWithIdentifier.Any())
            {
                foreach (var batch in objectsWithIdentifier.Batch(500))
                {
                    existing.UnionWith(Read(new ORFilterElement<AssetClass>(
                        batch.Select(obj => AssetClassExposers.Identifier.Equal(obj.Identifier))
                            .ToArray()
                    )).Select(obj => obj.Identifier));
                }
            }

            // Create the remainder (objects not already existing)
            var SuccessfulItems = new List<AssetClass>();
            var failures = new Dictionary<string, Exception>();
            var objects = createObjects.Where(obj => string.IsNullOrWhiteSpace(obj.Identifier) || !existing.Contains(obj.Identifier))
                .ToDictionary(obj => string.IsNullOrWhiteSpace(obj.Identifier) ? Guid.NewGuid().ToString() : obj.Identifier);

            foreach (var batch in createObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    SuccessfulItems.Add(FromInstance(success));
                }
            }

            // If everything went fine, return the successful creations
            if (!existing.Any() && !failures.Any())
            {
                return SuccessfulItems;
            }

            // Otherwise, build and throw an exception
            var exceptionBuilder = new SdmBulkCrudException<AssetClass>.Builder();
            foreach (var obj in createObjects)
            {
                var objId = string.IsNullOrWhiteSpace(obj.Identifier)
                    ? SuccessfulItems.FirstOrDefault(s => s.Name == obj.Name)?.Identifier
                    : obj.Identifier;

                if (!string.IsNullOrWhiteSpace(obj.Identifier) && existing.Contains(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, new SdmCrudException<AssetClass>(obj, $"Could not create AssetClass with guid: '{obj.Identifier}', it already exists."));
                    continue;
                }

                if (objId != null && failures.ContainsKey(objId))
                {
                    exceptionBuilder.AddFailed(obj, failures[objId]);
                    continue;
                }

                exceptionBuilder.AddSuccessful(obj);
            }

            throw exceptionBuilder.Build();
        }

        public IReadOnlyCollection<AssetClass> CreateOrUpdate(IEnumerable<AssetClass> items)
        {
            if (items is null || !items.Any())
            {
                return Array.Empty<AssetClass>();
            }

            // Validate all objects that are not new have identifiers
            var invalidObjects = items.Where(obj => !obj.IsNew && string.IsNullOrWhiteSpace(obj.Identifier)).ToList();
            if (invalidObjects.Any())
            {
                throw new ArgumentException($"Cannot update {invalidObjects.Count} object(s) without identifiers.", nameof(items));
            }

            var successful = new List<AssetClass>();
            var exceptionBuilder = new SdmBulkCrudException<AssetClass>.Builder();
            var objects = items
                .Where(obj => !string.IsNullOrWhiteSpace(obj.Identifier))
                .ToDictionary(obj => obj.Identifier);

            foreach (var batch in items.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    var failedId = failure.Id.ToString();
                    if (objects.ContainsKey(failedId))
                    {
                        exceptionBuilder.AddFailed(objects[failedId], new CrudFailedException(result.TraceDataPerItem[failure]));
                    }
                }

                foreach (var success in result.SuccessfulItems)
                {
                    var item = FromInstance(success);
                    exceptionBuilder.AddSuccessful(item);
                    successful.Add(item);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successful;
        }

        public long Count(FilterElement<AssetClass> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			var domFilter = TranslateFullFilter(filter);
			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId.Id));
			return helper.DomInstances.Count(domFilter);
		}

		public long Count(IQuery<AssetClass> query)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			var domFilter = TranslateFullFilter(query.Filter);
			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId.Id));
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			return helper.DomInstances.Count(domQuery);
		}

		public IEnumerable<AssetClass> Read(FilterElement<AssetClass> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			var domFilter = TranslateFullFilter(filter);
			return Read(domFilter);
		}

		public IEnumerable<AssetClass> Read(IQuery<AssetClass> query)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			var domFilter = TranslateFullFilter(query.Filter);
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			return Read(domQuery);
		}

		public IEnumerable<IPagedResult<AssetClass>> ReadPaged(FilterElement<AssetClass> filter)
		{
			return ReadPaged(filter, 500);
		}

		public IEnumerable<IPagedResult<AssetClass>> ReadPaged(FilterElement<AssetClass> filter, int pageSize)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			if (pageSize <= 0)
			{
				throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
			}

			var domFilter = TranslateFullFilter(filter);
			var paging = ReadPaged(domFilter, pageSize).GetEnumerator();
			var moveNext = paging.MoveNext();
			var i = 0;
			while (moveNext)
			{
				var page = paging.Current.ToList();
				moveNext = paging.MoveNext();
				var result = new PagedResult<AssetClass>(page, i, pageSize, moveNext);
				yield return result;
				i++;
			}
		}

		public IEnumerable<IPagedResult<AssetClass>> ReadPaged(IQuery<AssetClass> query)
		{
			return ReadPaged(query, 500);
		}

		public IEnumerable<IPagedResult<AssetClass>> ReadPaged(IQuery<AssetClass> query, int pageSize)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			if (pageSize <= 0)
			{
				throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
			}

			var domFilter = TranslateFullFilter(query.Filter);
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			var paging = ReadPaged(domQuery, pageSize).GetEnumerator();
			var moveNext = paging.MoveNext();
			var i = 0;
			while (moveNext)
			{
				var page = paging.Current.ToList();
				moveNext = paging.MoveNext();
				var result = new PagedResult<AssetClass>(page, i, pageSize, moveNext);
				yield return result;
				i++;
			}
		}

		public AssetClass Update(AssetClass updateObject)
		{
			if (updateObject is null)
			{
				throw new ArgumentNullException(nameof(updateObject));
			}

			if (string.IsNullOrWhiteSpace(updateObject.Identifier))
			{
				throw new ArgumentException("Cannot update an object without an identifier.", nameof(updateObject));
			}

			var instance = ToInstance(updateObject);
			instance = helper.DomInstances.Update(instance);
			return FromInstance(instance);
		}

        public IReadOnlyCollection<AssetClass> Update(IEnumerable<AssetClass> updateObjects)
        {
            if (updateObjects is null || !updateObjects.Any())
            {
                return Array.Empty<AssetClass>();
            }

            // Validate all objects have identifiers
            var objectsWithoutId = updateObjects.Where(obj => string.IsNullOrWhiteSpace(obj.Identifier)).ToList();
            if (objectsWithoutId.Any())
            {
                throw new ArgumentException($"Cannot update {objectsWithoutId.Count} object(s) without identifiers.", nameof(updateObjects));
            }

            // Check which objects already exist
            var existing = new HashSet<string>();
            foreach (var batch in updateObjects.Batch(500))
            {
                existing.UnionWith(Read(new ORFilterElement<AssetClass>(batch.Select(obj => AssetClassExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
            }

            // Update the existing objects
            var successfulItems = new List<AssetClass>();
            var failures = new Dictionary<string, Exception>();
            var objects = updateObjects.Where(obj => existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
            foreach (var batch in updateObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    successfulItems.Add(FromInstance(success));
                }
            }

            // Check for failures and build exception if needed
            var exceptionBuilder = new SdmBulkCrudException<AssetClass>.Builder();
            foreach (var obj in updateObjects)
            {
                if (!existing.Contains(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, new SdmCrudException<AssetClass>(obj, "Could not update a non existing AssetClass"));
                    continue;
                }

                if (failures.ContainsKey(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
                    continue;
                }

                exceptionBuilder.AddSuccessful(obj);
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successfulItems;
        }

        public void Delete(AssetClass deleteObject)
        {
            if (deleteObject is null)
            {
                throw new ArgumentNullException(nameof(deleteObject));
            }

            if (string.IsNullOrWhiteSpace(deleteObject.Identifier))
            {
                throw new ArgumentException("Cannot delete an object without an identifier.", nameof(deleteObject));
            }

            var instance = ToInstance(deleteObject);
            helper.DomInstances.Delete(instance);
        }

        public void Delete(IEnumerable<AssetClass> deleteObjects)
        {
            if (deleteObjects is null || !deleteObjects.Any())
            {
                return;
            }

            // Validate all objects have identifiers
            var objectsWithoutId = deleteObjects.Where(obj => string.IsNullOrWhiteSpace(obj.Identifier)).ToList();
            if (objectsWithoutId.Any())
            {
                throw new ArgumentException($"Cannot delete {objectsWithoutId.Count} object(s) without identifiers.", nameof(deleteObjects));
            }

            var exceptionBuilder = new SdmBulkCrudException<AssetClass>.Builder();
            var objects = deleteObjects.ToDictionary(obj => obj.Identifier);
            foreach (var batch in deleteObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryDelete(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulIds)
                {
                    exceptionBuilder.AddSuccessful(objects[success.Id.ToString()]);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }
        }

        private IEnumerable<AssetClass> Read(FilterElement<DomInstance> domFilter)
		{
			if (domFilter is null)
			{
				throw new ArgumentNullException(nameof(domFilter));
			}

			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId.Id));
			var domInstances = helper.DomInstances.Read(domFilter);
			return domInstances.Select(FromInstance);
		}

		private IEnumerable<AssetClass> Read(IQuery<DomInstance> domQuery)
		{
			if (domQuery is null)
			{
				throw new ArgumentNullException(nameof(domQuery));
			}

			var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId.Id));
			domQuery = domQuery.WithFilter(domFilter);
			var domInstances = helper.DomInstances.Read(domQuery);
			return domInstances.Select(FromInstance);
		}

		private IEnumerable<IEnumerable<AssetClass>> ReadPaged(FilterElement<DomInstance> domFilter, int pageSize)
		{
			if (domFilter is null)
			{
				throw new ArgumentNullException(nameof(domFilter));
			}

			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId.Id));
			var pagingHelper = helper.DomInstances.PreparePaging(domFilter, pageSize);
			while (pagingHelper.MoveToNextPage())
			{
				yield return pagingHelper.GetCurrentPage().Select(FromInstance);
			}
		}

		private IEnumerable<IEnumerable<AssetClass>> ReadPaged(IQuery<DomInstance> domQuery, int pageSize)
		{
			if (domQuery is null)
			{
				throw new ArgumentNullException(nameof(domQuery));
			}

			var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId.Id));
			domQuery = domQuery.WithFilter(domFilter);
			var pagingHelper = helper.DomInstances.PreparePaging(domQuery, pageSize);
			while (pagingHelper.MoveToNextPage())
			{
				yield return pagingHelper.GetCurrentPage().Select(FromInstance);
			}
		}

		private FilterElement<DomInstance> TranslateFullFilter(FilterElement<AssetClass> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			FilterElement<DomInstance> translated;
			if (filter is ANDFilterElement<AssetClass> and)
			{
				translated = new ANDFilterElement<DomInstance>(and.subFilters.Select(TranslateFullFilter).ToArray());
			}
			else if (filter is ORFilterElement<AssetClass> or)
			{
				translated = new ORFilterElement<DomInstance>(or.subFilters.Select(TranslateFullFilter).ToArray());
			}
			else if (filter is NOTFilterElement<AssetClass> not)
			{
				translated = new NOTFilterElement<DomInstance>(TranslateFullFilter(not));
			}
			else if (filter is TRUEFilterElement<AssetClass>)
			{
				translated = new TRUEFilterElement<DomInstance>();
			}
			else if (filter is FALSEFilterElement<AssetClass>)
			{
				translated = new FALSEFilterElement<DomInstance>();
			}
			else if (filter is ManagedFilterIdentifier managedFilter)
			{
				translated = TranslateFilter(managedFilter);
			}
			else
			{
				throw new NotSupportedException($"Unsupported filter: {filter}");
			}

			return translated;
		}

		private IOrderBy TranslateFullOrderBy(IOrderBy order)
		{
			if (order is null)
			{
				throw new ArgumentNullException(nameof(order));
			}

			var translatedElements = new List<IOrderByElement>();
			foreach (var orderByElement in order.Elements)
			{
				var translated = TranslateOrderBy(orderByElement);
				translatedElements.Add(translated);
			}

			return new OrderBy(translatedElements);
		}

		private FilterElement<DomInstance> TranslateFilter(ManagedFilterIdentifier managedFilter)
		{
			if (managedFilter is null)
			{
				throw new ArgumentNullException(nameof(managedFilter));
			}

			var fieldName = managedFilter.getFieldName().fieldName;
			var comparer = managedFilter.getComparer();
			var value = managedFilter.getValue();
			var translated = CreateFilter(fieldName, comparer, value);
			return translated;
		}

		private IOrderByElement TranslateOrderBy(IOrderByElement orderByElement)
		{
			if (orderByElement is null)
			{
				throw new ArgumentNullException(nameof(orderByElement));
			}

			var fieldName = orderByElement.Exposer.fieldName;
			var sortOrder = orderByElement.SortOrder;
			var naturalSort = orderByElement.Options.NaturalSort;
			var translated = CreateOrderBy(fieldName, sortOrder, naturalSort);
			return translated;
		}

		private AssetClass FromInstance(DomInstance instance)
		{
			var obj = new AssetClass
			{
				Identifier = instance.ID.Id.ToString()
			};
			var _assetclasspropertiesSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.SectionDefinitionId));
			if (_assetclasspropertiesSection != default)
			{
				var _devicename = _assetclasspropertiesSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceName);
				if (_devicename != null)
				{
					obj.Name = _devicename.Value;
				}

				var _deviceType = _assetclasspropertiesSection.GetValue<System.Guid>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceType);
				if (_deviceType != null)
				{
					obj.DeviceTypeId = new Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.SDM.AssetManagement.Models.DeviceType>(Convert.ToString(_deviceType.Value));
				}

				var _manufacturer = _assetclasspropertiesSection.GetValue<System.Guid>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Manufacturer);
				if (_manufacturer != null)
				{
					obj.Manufacturer = _manufacturer.Value;
				}

				var _devicedescription = _assetclasspropertiesSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceDescription);
				if (_devicedescription != null)
				{
					obj.Description = _devicedescription.Value;
				}

				var _depth = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Depth);
				if (_depth != null)
				{
					obj.Depth = _depth.Value;
				}

				var _height = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Height);
				if (_height != null)
				{
					obj.Height = _height.Value;
				}

				var _width = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Width);
				if (_width != null)
				{
					obj.Width = _width.Value;
				}

				var _heightu = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.HeightU);
				if (_heightu != null)
				{
					obj.HeightU = _heightu.Value;
				}

				var _weight = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Weight);
				if (_weight != null)
				{
					obj.Weight = _weight.Value;
				}

				var _frontimage = _assetclasspropertiesSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.FrontImage);
				if (_frontimage != null)
				{
					obj.FrontImage = _frontimage.Value;
				}

				var _backimage = _assetclasspropertiesSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.BackImage);
				if (_backimage != null)
				{
					obj.BackImage = _backimage.Value;
				}

				var _typicalpowerconsumption = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.TypicalPowerConsumption);
				if (_typicalpowerconsumption != null)
				{
					obj.TypicalPowerConsumption = _typicalpowerconsumption.Value;
				}

				var _maximumpowerconsumption = _assetclasspropertiesSection.GetValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.MaximumPowerConsumption);
				if (_maximumpowerconsumption != null)
				{
					obj.MaximumPowerConsumption = _maximumpowerconsumption.Value;
				}

				var _powersupply = _assetclasspropertiesSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.PowerSupply);
				if (_powersupply != null)
				{
					obj.PowerSupply = (SharedMappers.DomIds.SlcAsset_Management.Enums.PowerSupplyEnum)Enum.Parse(typeof(SharedMappers.DomIds.SlcAsset_Management.Enums.PowerSupplyEnum), _powersupply.Value);
				}
			}

			var _lifecycleSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.SectionDefinitionId));
			if (_lifecycleSection != default)
			{
				obj.Lifecycle = new Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassLifecycle();
				var _lifecycleendoflife = _lifecycleSection.GetValue<DateTime>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfLife);
				if (_lifecycleendoflife != null)
				{
					obj.Lifecycle.EndOfLife = (DateTime)_lifecycleendoflife.Value;
				}

				var _lifecycleendofservice = _lifecycleSection.GetValue<DateTime>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfService);
				if (_lifecycleendofservice != null)
				{
					obj.Lifecycle.EndOfService = (DateTime)_lifecycleendofservice.Value;
				}

				var _lifecyclenominallifetime = _lifecycleSection.GetValue<TimeSpan>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.NominalLifetime);
				if (_lifecyclenominallifetime != null)
				{
					obj.Lifecycle.NominalLifetime = (TimeSpan)_lifecyclenominallifetime.Value;
				}
			}

			var _dataportsList = new System.Collections.Generic.List<Skyline.DataMiner.SDM.AssetManagement.Models.DataPortInfo>();
			foreach (var _dataportsSection in instance.Sections.Where(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.SectionDefinitionId)))
			{
                var dataports = new Skyline.DataMiner.SDM.AssetManagement.Models.DataPortInfo();

				var _dataportsname = _dataportsSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Name);
				if (_dataportsname != null)
				{
					dataports.Name = _dataportsname.Value;
				}

				var _dataportsportnumber = _dataportsSection.GetValue<long>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortNumber);
				if (_dataportsportnumber != null)
				{
					dataports.PortNumber = _dataportsportnumber.Value;
				}

				var _dataportsoutputtype = _dataportsSection.GetValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.OutputType);
				if (_dataportsoutputtype != null)
				{
					dataports.OutputType = (SharedMappers.DomIds.SlcAsset_Management.Enums.Outputtype)_dataportsoutputtype.Value;
				}

				var _dataportsportexposure = _dataportsSection.GetValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortExposure);
				if (_dataportsportexposure != null)
				{
					dataports.PortExposure = (SharedMappers.DomIds.SlcAsset_Management.Enums.PortExposureEnum)_dataportsportexposure.Value;
				}

				var _dataportstype = _dataportsSection.GetValue<Guid>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Type);
				if (_dataportstype != null)
				{
                    dataports.Type = new SdmObjectReference<PortType>(Convert.ToString(_dataportstype.Value));
				}

				var _dataportslabel = _dataportsSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Label);
				if (_dataportslabel != null)
				{
					dataports.Label = _dataportslabel.Value;
				}

				_dataportsList.Add(dataports);
			}

			obj.DataPorts = _dataportsList;
			var _powerportsList = new System.Collections.Generic.List<Skyline.DataMiner.SDM.AssetManagement.Models.PowerPortInfo>();
			foreach (var _powerportsSection in instance.Sections.Where(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.SectionDefinitionId)))
			{
                var powerports = new Skyline.DataMiner.SDM.AssetManagement.Models.PowerPortInfo();

				var _powerportsname = _powerportsSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Name);
				if (_powerportsname != null)
				{
					powerports.Name = _powerportsname.Value;
				}

				var _powerportsportnumber = _powerportsSection.GetValue<long>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortNumber);
				if (_powerportsportnumber != null)
				{
					powerports.PortNumber = _powerportsportnumber.Value;
				}

				var _powerportsoutputtype = _powerportsSection.GetValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.OutputType);
				if (_powerportsoutputtype != null)
				{
					powerports.OutputType = (SharedMappers.DomIds.SlcAsset_Management.Enums.Outputtype)_powerportsoutputtype.Value;
				}

				var _powerportsportexposure = _powerportsSection.GetValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortExposure);
				if (_powerportsportexposure != null)
				{
					powerports.PortExposure = (SharedMappers.DomIds.SlcAsset_Management.Enums.PortExposureEnum)_powerportsportexposure.Value;
				}

				var _powerportsporttype = _powerportsSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortType);
				if (_powerportsporttype != null)
				{
					powerports.PortType = System.Guid.Parse(Convert.ToString(_powerportsporttype.Value));
				}

				var _powerportslabel = _powerportsSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Label);
				if (_powerportslabel != null)
				{
					powerports.Label = _powerportslabel.Value;
				}

				_powerportsList.Add(powerports);
			}

			obj.PowerPorts = _powerportsList;
			var _holdersList = new System.Collections.Generic.List<Skyline.DataMiner.SDM.AssetManagement.Models.AssetHolder>();
			foreach (var _holdersSection in instance.Sections.Where(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.SectionDefinitionId)))
			{
                var holders = new Skyline.DataMiner.SDM.AssetManagement.Models.AssetHolder();
				var _holdersslotnumber = _holdersSection.GetValue<long>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.SlotNumber);
				if (_holdersslotnumber != null)
				{
					holders.SlotNumber = _holdersslotnumber.Value;
				}

				var _holdershierarchyrole = _holdersSection.GetValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.HierarchyRole);
				if (_holdershierarchyrole != null)
				{
					holders.HierarchyRole = SlcAsset_Management.Enums.Hierarchyrole.ToEnum(_holdershierarchyrole.Value);
				}

				_holdersList.Add(holders);
			}

			obj.Holders = _holdersList;
            obj.IsNew = false;
            obj.ResetChangeTracking();

			return obj;
		}

		private DomInstance ToInstance(AssetClass obj)
		{
			Guid id = default(Guid);
			if (!String.IsNullOrEmpty(obj.Identifier))
			{
				id = Guid.Parse(obj.Identifier);
			}
			else
			{
				id = Guid.NewGuid();
			}

			var instance = new DomInstance
			{
				DomDefinitionId = Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DomDefinitionId,
				ID = new DomInstanceId(id)
				{
					ModuleId = Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.ModuleId
				}
			};
			var _assetclassproperties = new Section(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.SectionDefinitionId);
			if (obj.Name != default)
			{
				_assetclassproperties.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceName, Convert.ToString(obj.Name));
			}

			if (obj.DeviceTypeId != default)
			{
				_assetclassproperties.AddOrUpdateValue<System.Guid>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceType, System.Guid.Parse(obj.DeviceTypeId.Identifier));
			}

			if (obj.Manufacturer != default)
			{
				_assetclassproperties.AddOrUpdateValue<System.Guid>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Manufacturer, obj.Manufacturer);
			}

			if (obj.Description != default)
			{
				_assetclassproperties.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceDescription, Convert.ToString(obj.Description));
			}

			if (obj.Depth != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Depth, (double)obj.Depth);
			}

			if (obj.Height != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Height, (double)obj.Height);
			}

			if (obj.Width != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Width, (double)obj.Width);
			}

			if (obj.HeightU != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.HeightU, (double)obj.HeightU);
			}

			if (obj.Weight != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Weight, (double)obj.Weight);
			}

			if (obj.FrontImage != default)
			{
				_assetclassproperties.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.FrontImage, Convert.ToString(obj.FrontImage));
			}

			if (obj.BackImage != default)
			{
				_assetclassproperties.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.BackImage, Convert.ToString(obj.BackImage));
			}

			if (obj.TypicalPowerConsumption != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.TypicalPowerConsumption, (double)obj.TypicalPowerConsumption);
			}

			if (obj.MaximumPowerConsumption != default)
			{
				_assetclassproperties.AddOrUpdateValue<double>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.MaximumPowerConsumption, (double)obj.MaximumPowerConsumption);
			}

			if (obj.PowerSupply != default)
			{
				_assetclassproperties.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.PowerSupply, Convert.ToString(obj.PowerSupply));
			}

			instance.Sections.Add(_assetclassproperties);
			if (obj.Lifecycle != null)
			{
				var _lifecycle = new Section(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.SectionDefinitionId);
				if (obj.Lifecycle.EndOfLife != default)
				{
					_lifecycle.AddOrUpdateValue<DateTime>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfLife, (DateTime)obj.Lifecycle.EndOfLife);
				}

				if (obj.Lifecycle.EndOfService != default)
				{
					_lifecycle.AddOrUpdateValue<DateTime>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfService, (DateTime)obj.Lifecycle.EndOfService);
				}

				if (obj.Lifecycle.NominalLifetime != default)
				{
					_lifecycle.AddOrUpdateValue<TimeSpan>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.NominalLifetime, (TimeSpan)obj.Lifecycle.NominalLifetime);
				}

				instance.Sections.Add(_lifecycle);
			}

			foreach (var dataports in obj.DataPorts)
			{
                var _dataportsSection = new Section(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.SectionDefinitionId);

				if (dataports.Name != default)
				{
					_dataportsSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Name, Convert.ToString(dataports.Name));
				}

				if (dataports.PortNumber != default)
				{
					_dataportsSection.AddOrUpdateValue<long>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortNumber, (long)dataports.PortNumber);
				}

				_dataportsSection.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.OutputType, (int)dataports.OutputType);
				_dataportsSection.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortExposure, (int)dataports.PortExposure);
				if (dataports.Type != default)
				{
					_dataportsSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Type, Convert.ToString(dataports.Type));
				}

				if (dataports.Label != default)
				{
					_dataportsSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Label, Convert.ToString(dataports.Label));
				}

				instance.Sections.Add(_dataportsSection);
			}

			foreach (var powerports in obj.PowerPorts)
			{
				var _powerportsSection = new Section(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.SectionDefinitionId);

				if (powerports.Name != default)
				{
					_powerportsSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Name, Convert.ToString(powerports.Name));
				}

				if (powerports.PortNumber != default)
				{
					_powerportsSection.AddOrUpdateValue<long>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortNumber, (long)powerports.PortNumber);
				}

				_powerportsSection.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.OutputType, (int)powerports.OutputType);
				_powerportsSection.AddOrUpdateValue<int>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortExposure, (int)powerports.PortExposure);
				if (powerports.PortType != default)
				{
					_powerportsSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortType, Convert.ToString(powerports.PortType));
				}

				if (powerports.Label != default)
				{
					_powerportsSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Label, Convert.ToString(powerports.Label));
				}

				instance.Sections.Add(_powerportsSection);
			}

			foreach (var holders in obj.Holders)
			{
                var _holdersSection = new Section(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.SectionDefinitionId);

				if (holders.SlotNumber != default)
				{
					_holdersSection.AddOrUpdateValue<long>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.SlotNumber, (long)holders.SlotNumber);
				}

				_holdersSection.AddOrUpdateValue<string>(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.HierarchyRole, SlcAsset_Management.Enums.Hierarchyrole.ToValue(holders.HierarchyRole));
				instance.Sections.Add(_holdersSection);
			}

			return instance;
		}

		private FilterElement<DomInstance> CreateFilter(string fieldName, Comparer comparer, object value)
		{
			switch (fieldName)
			{
				case "Identifier":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.Id, comparer, Guid.Parse((string)value));
				case "Name":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceName), comparer, (string)value);
				case "DeviceTypeId":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceType), comparer, System.Guid.Parse(Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.SDM.AssetManagement.Models.DeviceType>.Convert(value).Identifier));
				case "Manufacturer":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Manufacturer), comparer, Convert.ToString((System.Guid)value));
				case "Description":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceDescription), comparer, (string)value);
				case "Depth":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Depth), comparer, (double)value);
				case "Height":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Height), comparer, (double)value);
				case "Width":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Width), comparer, (double)value);
               case "HeightU":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.HeightU), comparer, (double)value);
				case "Weight":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Weight), comparer, (double)value);
				case "FrontImage":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.FrontImage), comparer, (string)value);
				case "BackImage":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.BackImage), comparer, (string)value);
				case "TypicalPowerConsumption":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.TypicalPowerConsumption), comparer, (double)value);
				case "MaximumPowerConsumption":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.MaximumPowerConsumption), comparer, (double)value);
				case "PowerSupply":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.PowerSupply), comparer, (int)(SharedMappers.DomIds.SlcAsset_Management.Enums.PowerSupplyEnum)value);
				case "Lifecycle.EndOfLife":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfLife), comparer, (DateTime)(DateTime)value);
				case "Lifecycle.EndOfService":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfService), comparer, (DateTime)(DateTime)value);
				case "Lifecycle.NominalLifetime":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.NominalLifetime), comparer, (TimeSpan)(TimeSpan)value);
				case "DataPorts.Identifier":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.SectionIds, comparer, Guid.Parse((string)value));
				case "DataPorts.Name":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Name), comparer, (string)value);
				case "DataPorts.PortNumber":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortNumber), comparer, (long)value);
				case "DataPorts.OutputType":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.OutputType), comparer, (int)(SharedMappers.DomIds.SlcAsset_Management.Enums.Outputtype)value);
				case "DataPorts.PortExposure":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortExposure), comparer, (int)(SharedMappers.DomIds.SlcAsset_Management.Enums.PortExposureEnum)value);
				case "DataPorts.Type":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Type), comparer, Convert.ToString((System.Guid)value));
				case "DataPorts.Label":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Label), comparer, (string)value);
				case "PowerPorts.Identifier":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.SectionIds, comparer, Guid.Parse((string)value));
				case "PowerPorts.Name":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Name), comparer, (string)value);
				case "PowerPorts.PortNumber":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortNumber), comparer, (long)value);
				case "PowerPorts.OutputType":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.OutputType), comparer, (int)(SharedMappers.DomIds.SlcAsset_Management.Enums.Outputtype)value);
				case "PowerPorts.PortExposure":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortExposure), comparer, (int)(SlcAsset_Management.Enums.PortExposureEnum)value);
				case "PowerPorts.PortType":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortType), comparer, Convert.ToString((System.Guid)value));
				case "PowerPorts.Label":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Label), comparer, (string)value);
				case "Holders.Identifier":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.SectionIds, comparer, Guid.Parse((string)value));
				case "Holders.SlotNumber":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.SlotNumber), comparer, (long)value);
				case "Holders.HierarchyRole":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.HierarchyRole), comparer, (int)(SlcAsset_Management.Enums.HierarchyRoleEnum)value);
				default:
					throw new NotImplementedException();
			}
		}

		private IOrderByElement CreateOrderBy(string fieldName, SortOrder sortOrder, bool naturalSort = false)
		{
			switch (fieldName)
			{
				case "Identifier":
					return OrderByElementFactory.Create(DomInstanceExposers.Id, sortOrder, naturalSort);
				case "Name":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceName), sortOrder, naturalSort);
				case "DeviceTypeId":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceType), sortOrder, naturalSort);
				case "ManufacturerId":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Manufacturer), sortOrder, naturalSort);
				case "Description":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.DeviceDescription), sortOrder, naturalSort);
				case "Depth":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Depth), sortOrder, naturalSort);
				case "Height":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Height), sortOrder, naturalSort);
				case "Width":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Width), sortOrder, naturalSort);
				case "HeightU":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.HeightU), sortOrder, naturalSort);
				case "Weight":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.Weight), sortOrder, naturalSort);
				case "FrontImage":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.FrontImage), sortOrder, naturalSort);
				case "BackImage":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.BackImage), sortOrder, naturalSort);
				case "TypicalPowerConsumption":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.TypicalPowerConsumption), sortOrder, naturalSort);
				case "MaximumPowerConsumption":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.MaximumPowerConsumption), sortOrder, naturalSort);
				case "PowerSupply":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.AssetClassProperties.PowerSupply), sortOrder, naturalSort);
				case "Lifecycle.EndOfLife":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfLife), sortOrder, naturalSort);
				case "Lifecycle.EndOfService":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.EndOfService), sortOrder, naturalSort);
				case "Lifecycle.NominalLifetime":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Lifecycle.NominalLifetime), sortOrder, naturalSort);
				case "DataPorts.Identifier":
					return OrderByElementFactory.Create(DomInstanceExposers.SectionIds, sortOrder, naturalSort);
				case "DataPorts.Name":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Name), sortOrder, naturalSort);
				case "DataPorts.PortNumber":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortNumber), sortOrder, naturalSort);
				case "DataPorts.OutputType":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.OutputType), sortOrder, naturalSort);
				case "DataPorts.PortExposure":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.PortExposure), sortOrder, naturalSort);
				case "DataPorts.Type":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Type), sortOrder, naturalSort);
				case "DataPorts.Label":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.DataPorts.Label), sortOrder, naturalSort);
				case "PowerPorts.Identifier":
					return OrderByElementFactory.Create(DomInstanceExposers.SectionIds, sortOrder, naturalSort);
				case "PowerPorts.Name":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Name), sortOrder, naturalSort);
				case "PowerPorts.PortNumber":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortNumber), sortOrder, naturalSort);
				case "PowerPorts.OutputType":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.OutputType), sortOrder, naturalSort);
				case "PowerPorts.PortExposure":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortExposure), sortOrder, naturalSort);
				case "PowerPorts.PortType":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.PortType), sortOrder, naturalSort);
				case "PowerPorts.Label":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.PowerPorts.Label), sortOrder, naturalSort);
				case "Holders.Identifier":
					return OrderByElementFactory.Create(DomInstanceExposers.SectionIds, sortOrder, naturalSort);
				case "Holders.SlotNumber":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.SlotNumber), sortOrder, naturalSort);
				case "Holders.HierarchyRole":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.SDM.AssetManagement.Models.AssetClassDomMapper.Holders.HierarchyRole), sortOrder, naturalSort);
				default:
					throw new NotImplementedException();
			}
		}
	}
}