//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Linq;

    using SharedMappers.DomIds;

    using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.SDM;
	using Skyline.DataMiner.SDM.Exposers;
	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	public static partial class AssetClassExposers
	{
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Identifier = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.Identifier, "Identifier");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid> Id = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid>((obj) => obj.Id, "Id");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> DeviceName = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.Name, "DeviceName");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.SDM.AssetManagement.Models.DeviceType>> DeviceTypeId = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.SDM.AssetManagement.Models.DeviceType>>((obj) => obj.DeviceTypeId, "DeviceTypeId");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> DeviceDescription = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.Description, "DeviceDescription");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid> ManufacturerId = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid>((obj) => obj.Manufacturer, "Manufacturer");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> Depth = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.Depth, "Depth");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> Height = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.Height, "Height");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> Width = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.Width, "Width");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> HeightU = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.HeightU, "HeightU");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> Weight = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.Weight, "Weight");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> FrontImage = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.FrontImage, "FrontImage");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> BackImage = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.BackImage, "BackImage");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> TypicalPowerConsumption = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.TypicalPowerConsumption, "TypicalPowerConsumption");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double> MaximumPowerConsumption = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, double>((obj) => obj.MaximumPowerConsumption, "MaximumPowerConsumption");
		public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.PowerSupplyEnum> PowerSupply = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.PowerSupplyEnum>((obj) => obj.PowerSupply, "PowerSupply");
		public static partial class Lifecycle
		{
			public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, DateTime> EndOfLife = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, DateTime>((obj) => obj.Lifecycle.EndOfLife, "Lifecycle.EndOfLife");
			public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, DateTime> EndOfService = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, DateTime>((obj) => obj.Lifecycle.EndOfService, "Lifecycle.EndOfService");
			public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, TimeSpan> NominalLifetime = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, TimeSpan>((obj) => obj.Lifecycle.NominalLifetime, "Lifecycle.NominalLifetime");
		}

		public static partial class DataPorts
		{
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Identifier = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.Identifier).Where(x => x != null), "DataPorts.Identifier");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Name = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.DataPortInfo.Name).Where(x => x != null), "DataPorts.Name");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, long> PortNumber = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, long>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.DataPortInfo.PortNumber), "DataPorts.PortNumber");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.Outputtype> OutputType = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.Outputtype>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.DataPortInfo.OutputType), "DataPorts.OutputType");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.PortExposureEnum> PortExposure = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.PortExposureEnum>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.DataPortInfo.PortExposure), "DataPorts.PortExposure");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid> Type = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.DataPortInfo.Type).Where(x => x != null), "DataPorts.Type");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Label = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.DataPorts.Where(x => x != null).Select(x => x.DataPortInfo.Label).Where(x => x != null), "DataPorts.Label");
		}

		public static partial class PowerPorts
		{
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Identifier = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.Identifier).Where(x => x != null), "PowerPorts.Identifier");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Name = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.PowerPortInfo.Name).Where(x => x != null), "PowerPorts.Name");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, long> PortNumber = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, long>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.PowerPortInfo.PortNumber), "PowerPorts.PortNumber");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.Outputtype> OutputType = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.Outputtype>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.PowerPortInfo.OutputType), "PowerPorts.OutputType");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.PortExposureEnum> PortExposure = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.PortExposureEnum>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.PowerPortInfo.PortExposure), "PowerPorts.PortExposure");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid> PortType = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, System.Guid>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.PowerPortInfo.PortType).Where(x => x != null), "PowerPorts.PortType");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Label = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.PowerPorts.Where(x => x != null).Select(x => x.PowerPortInfo.Label).Where(x => x != null), "PowerPorts.Label");
		}

		public static partial class Holders
		{
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string> Identifier = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, string>((obj) => obj.Holders.Where(x => x != null).Select(x => x.Identifier).Where(x => x != null), "Holders.Identifier");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, long> SlotNumber = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, long>((obj) => obj.Holders.Where(x => x != null).Select(x => x.SlotNumber), "Holders.SlotNumber");
			public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.HierarchyRoleEnum> HierarchyRole = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.AssetClass, SlcAsset_Management.Enums.HierarchyRoleEnum>((obj) => obj.Holders.Where(x => x != null).Select(x => x.HierarchyRole), "Holders.HierarchyRole");
		}
	}
}