//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;

    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;

    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class CableTypeExposers
    {
        public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, string> Identifier = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, string>((obj) => obj.Identifier, "Identifier");
        public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, string> Name = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, string>((obj) => obj.Name, "Name");
        public static readonly Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, string> Description = new Exposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, string>((obj) => obj.Description, "Description");
        static CableTypeExposers()
        {
            RuntimeHelpers.RunClassConstructor(typeof(CategoryLinks).TypeHandle);
        }

        public static partial class CategoryLinks
        {
            public static readonly CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, SharedMappers.DomIds.SlcAsset_Management.Enums.CategoriesEnum> Categories = new CollectionExposer<Skyline.DataMiner.SDM.AssetManagement.Models.CableType, SharedMappers.DomIds.SlcAsset_Management.Enums.CategoriesEnum>((obj) => obj.CategoryLinks.Categories.Where(x => x != null), "CategoryLinks.Categories");
        }
    }
}