//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SharedMappers.DomIds
{
	using System;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcFacility_Management
	{
		public const string ModuleId = "(slc)facility_management";
		public static class Enums
		{
			public static class Facilitytype
			{
				public const string Truck = "Truck";
				public const string Container = "Container";
				public const string Building = "Building";
				public static string ToValue(FacilityTypeEnum @enum)
				{
					switch (@enum)
					{
						case FacilityTypeEnum.Truck:
							return Truck;
						case FacilityTypeEnum.Container:
							return Container;
						case FacilityTypeEnum.Building:
							return Building;
						default:
							throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
					}
				}

				public static FacilityTypeEnum ToEnum(string s)
				{
					switch (s)
					{
						case Truck:
							return FacilityTypeEnum.Truck;
						case Container:
							return FacilityTypeEnum.Container;
						case Building:
							return FacilityTypeEnum.Building;
						default:
							throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
					}
				}
			}

			public enum FacilityTypeEnum
			{
				Truck,
				Container,
				Building
			}

			public enum ThermalType
			{
				None = 0,
				Warm = 1,
				Cold = 2
			}

			public static class Rackpositionenum
			{
				public const string Bottom = "Bottom";
				public const string Top = "Top";
				public static string ToValue(RackpositionenumEnum @enum)
				{
					switch (@enum)
					{
						case RackpositionenumEnum.Bottom:
							return Bottom;
						case RackpositionenumEnum.Top:
							return Top;
						default:
							throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
					}
				}

				public static RackpositionenumEnum ToEnum(string s)
				{
					switch (s)
					{
						case Bottom:
							return RackpositionenumEnum.Bottom;
						case Top:
							return RackpositionenumEnum.Top;
						default:
							throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
					}
				}
			}

			public enum RackpositionenumEnum
			{
				Bottom,
				Top
			}

			public static class Coolingflowenum
			{
				public const string FrontToRear = "Front To Rear";
				public const string RearToFront = "Rear To Front";
				public const string SideToSide = "Side To Side";
				public const string TopToBottom = "Top To Bottom";
				public const string BottomToTop = "Bottom To Top";
				public static string ToValue(CoolingflowenumEnum @enum)
				{
					switch (@enum)
					{
						case CoolingflowenumEnum.FrontToRear:
							return FrontToRear;
						case CoolingflowenumEnum.RearToFront:
							return RearToFront;
						case CoolingflowenumEnum.SideToSide:
							return SideToSide;
						case CoolingflowenumEnum.TopToBottom:
							return TopToBottom;
						case CoolingflowenumEnum.BottomToTop:
							return BottomToTop;
						default:
							throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
					}
				}

				public static CoolingflowenumEnum ToEnum(string s)
				{
					switch (s)
					{
						case FrontToRear:
							return CoolingflowenumEnum.FrontToRear;
						case RearToFront:
							return CoolingflowenumEnum.RearToFront;
						case SideToSide:
							return CoolingflowenumEnum.SideToSide;
						case TopToBottom:
							return CoolingflowenumEnum.TopToBottom;
						case BottomToTop:
							return CoolingflowenumEnum.BottomToTop;
						default:
							throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
					}
				}
			}

			public enum CoolingflowenumEnum
			{
				FrontToRear,
				RearToFront,
				SideToSide,
				TopToBottom,
				BottomToTop
			}

			public enum Placementorientationenum
			{
				Vertical = 0,
				Horizontal = 1
			}
		}

		public static class Sections
		{
			public static class ImageInfo
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("67f72a06-cb71-4a21-9973-0ba04e966be9"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID ImageFilepath
				{
					get;
				}

				= new FieldDescriptorID(new Guid("8498450a-7200-4e7f-b750-7c57dd3a7437"));
				public static FieldDescriptorID UploadTimestamp
				{
					get;
				}

				= new FieldDescriptorID(new Guid("29d8c8da-00d8-46fa-adff-d7979d3a5665"));
			}

			public static class Site
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("9a6552d4-c538-45be-93fd-a879587d25cc"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Site_f08b42c7
				{
					get;
				}

				= new FieldDescriptorID(new Guid("f08b42c7-0c43-42f3-9c93-ec69ee99501a"));
			}

			public static class SiteInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("b082f391-0fdd-4eda-b4dc-f246c5e0063f"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("49e5f5af-555a-4aa6-b859-84b3d6c4016d"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("199e9b2a-737c-4ddf-bb9e-ae41dff3d4ba"));
				public static FieldDescriptorID Address
				{
					get;
				}

				= new FieldDescriptorID(new Guid("54866065-c005-4b3e-a8af-9d73b31fbcc7"));
				public static FieldDescriptorID City
				{
					get;
				}

				= new FieldDescriptorID(new Guid("a5871ad2-0caf-4d1f-9ae1-9bbd91e9e158"));
				public static FieldDescriptorID ZipCode
				{
					get;
				}

				= new FieldDescriptorID(new Guid("22ea6e74-8beb-445c-9e28-c96e7d11986d"));
				public static FieldDescriptorID Country
				{
					get;
				}

				= new FieldDescriptorID(new Guid("0b43ef7a-64c3-4757-ae2b-089117316738"));
				public static FieldDescriptorID Latitude
				{
					get;
				}

				= new FieldDescriptorID(new Guid("fd3feeaf-9d1e-4752-a1ba-5da40ed16793"));
				public static FieldDescriptorID Longitude
				{
					get;
				}

				= new FieldDescriptorID(new Guid("3f7b64ea-7cd7-4e84-8f80-ab69064a93a8"));
				public static FieldDescriptorID SiteID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("e9485c2b-accd-4eda-9b86-195540a9cd20"));
			}

			public static class FacilityInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("125d4f2c-4d9f-4efe-9af6-1e6a5d4bcaab"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("259e31ed-65e9-4a1f-b8f9-20d94e3e09b3"));
				public static FieldDescriptorID FacilityType
				{
					get;
				}

				= new FieldDescriptorID(new Guid("37dbb06b-efcd-4295-a646-00ee1eb30d01"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("fd4dbb48-ed5a-4fc7-bf49-a1f119d09883"));
				public static FieldDescriptorID Address
				{
					get;
				}

				= new FieldDescriptorID(new Guid("370f8d27-5ce8-4308-ae3e-130c9dbbf366"));
				public static FieldDescriptorID City
				{
					get;
				}

				= new FieldDescriptorID(new Guid("4fa9677f-0022-4012-b371-c884840db7ea"));
				public static FieldDescriptorID ZipCode
				{
					get;
				}

				= new FieldDescriptorID(new Guid("91359fc6-ffa8-47b5-a849-20036307a3d8"));
				public static FieldDescriptorID Country
				{
					get;
				}

				= new FieldDescriptorID(new Guid("613d7d84-8d85-4e29-9af8-9dc752208789"));
				public static FieldDescriptorID Latitude
				{
					get;
				}

				= new FieldDescriptorID(new Guid("def40fd7-3d08-4f1b-88e8-e95ce0ca2606"));
				public static FieldDescriptorID Longitude
				{
					get;
				}

				= new FieldDescriptorID(new Guid("872360fb-bc51-46c6-bfd0-8282c6a913f6"));
				public static FieldDescriptorID FacilityID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("4ca5dc9c-4bb5-4e46-8a95-0bcf95d2265c"));
			}

			public static class RowInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("12edb830-c667-4e93-9f9b-94e6992a3bf6"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("12ee587f-e9bf-4be8-8ec7-2c04ac3340dd"));
				public static FieldDescriptorID RowPlan
				{
					get;
				}

				= new FieldDescriptorID(new Guid("335719a3-5c1a-4a03-93f2-33fb8b13cedc"));
				public static FieldDescriptorID RowDescription
				{
					get;
				}

				= new FieldDescriptorID(new Guid("73b46987-4318-4985-8694-1ef510d96ce1"));
				public static FieldDescriptorID Y
				{
					get;
				}

				= new FieldDescriptorID(new Guid("3c56aa07-ba3b-4e62-b7ab-46d4d9bce19d"));
				public static FieldDescriptorID Label
				{
					get;
				}

				= new FieldDescriptorID(new Guid("ca234e07-2ea4-4d69-aa94-6136a22e9047"));
				public static FieldDescriptorID RowID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("808a94ba-3c5b-4018-88c2-73f1bcebf0f0"));
			}

			public static class RackCapacity
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("790bcbea-9659-4340-91ff-46dc8c37b251"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID MaximumRackCapacity
				{
					get;
				}

				= new FieldDescriptorID(new Guid("be8b9be1-277a-4ccc-ae10-f771900f2847"));
				public static FieldDescriptorID MaximumPowerCapacity
				{
					get;
				}

				= new FieldDescriptorID(new Guid("fead1e27-0d5b-43b2-b95b-963343140e1e"));
			}

			public static class AppSettings
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("67ba4303-7c6b-4c2c-bb8b-0fb2fb4d970d"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID GoogleMapsAPIKey
				{
					get;
				}

				= new FieldDescriptorID(new Guid("b4d1d0e7-a4be-45e6-8ab8-b1922a82d21f"));
			}

			public static class ZoneCapacity
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("136914bb-3580-450f-ad38-3bb709ddc68f"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID CoolingCapacity
				{
					get;
				}

				= new FieldDescriptorID(new Guid("814e6ce1-8cb7-4517-b8cd-1ed9e896ca6a"));
			}

			public static class Row
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("8a81a86b-7372-4c83-bde7-680004bb3eb4"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Row_5d2f9bb3
				{
					get;
				}

				= new FieldDescriptorID(new Guid("5d2f9bb3-a00b-4372-b079-0004b184e15c"));
			}

			public static class Floor
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("cdbc1f3d-70c8-49e3-a3a3-b310d20b4b6e"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Floor_6a3f0eeb
				{
					get;
				}

				= new FieldDescriptorID(new Guid("6a3f0eeb-018c-412e-a889-819fc83205a4"));
			}

			public static class Room
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("3ee83337-fe05-417e-b328-08a7931da62f"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Room_8d904f8d
				{
					get;
				}

				= new FieldDescriptorID(new Guid("8d904f8d-6340-4d7e-abc8-62ac1e3fcb09"));
			}

			public static class Zone
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("785e2397-0f0e-4b82-ace6-9e372a208bf6"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Zone_45922fd2
				{
					get;
				}

				= new FieldDescriptorID(new Guid("45922fd2-c869-46ac-a95d-012fad5adb59"));
			}

			public static class Resource
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("2f8f34af-8405-4a7e-b996-da6b9d97e61c"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID LinkedResource
				{
					get;
				}

				= new FieldDescriptorID(new Guid("af0981cf-d4c0-4016-823b-bd34a385aa2e"));
			}

			public static class DeskInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("20bcc5d1-5065-4091-a5b0-82a09ecb9ddb"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("bc96a0b4-a8b3-42cc-8a23-eec98f078301"));
				public static FieldDescriptorID Plan
				{
					get;
				}

				= new FieldDescriptorID(new Guid("ef68805b-86c2-47d3-9b28-2a0d480b7712"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("2291fc00-8995-4faf-be6e-5da359d38dc7"));
				public static FieldDescriptorID DeskID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("488edf47-1b9f-4083-bd6d-8f47fe5bb20e"));
			}

			public static class ZoneInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("8d225b1a-d69c-4efa-86c3-7f45d6ea7e92"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("f1a7cc3d-634c-452c-a27e-68d704d321f7"));
				public static FieldDescriptorID Plan
				{
					get;
				}

				= new FieldDescriptorID(new Guid("574e51c6-4e1a-4729-b33f-b00a8e558ed2"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("e72ceb4a-501b-4781-88b8-97b52b6f7a1a"));
				public static FieldDescriptorID ThermalType
				{
					get;
				}

				= new FieldDescriptorID(new Guid("eabd3474-9983-4475-be2f-ddd3dca76137"));
				public static FieldDescriptorID X
				{
					get;
				}

				= new FieldDescriptorID(new Guid("9b1ac3ee-18d4-44d8-8cf0-bdf6bf09f6f8"));
				public static FieldDescriptorID Y
				{
					get;
				}

				= new FieldDescriptorID(new Guid("2c5edc9a-c1fd-4c9b-9118-e6f6f0e956d8"));
				public static FieldDescriptorID Width
				{
					get;
				}

				= new FieldDescriptorID(new Guid("69bb8e71-81ff-4195-ab5a-427bcde57350"));
				public static FieldDescriptorID Depth
				{
					get;
				}

				= new FieldDescriptorID(new Guid("d9ed302e-9752-4680-9b1e-8af3db9f9c9e"));
				public static FieldDescriptorID ZoneID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("10cc0744-6b35-4d9c-9158-47f0f2c9fdb7"));
			}

			public static class RoomInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("45f3a9f1-93ca-486b-99f2-70c00f8f80ec"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("995923a7-0220-4a0f-89c0-7f0856c18661"));
				public static FieldDescriptorID Plan
				{
					get;
				}

				= new FieldDescriptorID(new Guid("bcdd4b85-0b08-4991-b351-e7d4d6165638"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("4c12f63d-5184-4e0b-9213-ca8ca448b23f"));
				public static FieldDescriptorID Width
				{
					get;
				}

				= new FieldDescriptorID(new Guid("31249cdc-4817-46be-b288-481cbefeb2df"));
				public static FieldDescriptorID Depth
				{
					get;
				}

				= new FieldDescriptorID(new Guid("11dede73-1ca8-419b-87db-1e78c50317c6"));
				public static FieldDescriptorID RoomID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("16beb7ef-8fde-41e3-9f84-318fd8aa68e4"));
			}

			public static class FloorInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("f3b701eb-5ae6-4cb3-8207-b11c7801e136"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("330ac9f6-5da1-4a3b-b1ed-99179e10d708"));
				public static FieldDescriptorID Plan
				{
					get;
				}

				= new FieldDescriptorID(new Guid("1d3a2787-3c0a-4962-85c1-421969d1bbfc"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("eea022dd-636c-4719-ae09-7af4ad32cae7"));
				public static FieldDescriptorID FloorID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("3b996c01-2fa6-4443-a877-d9b2ecd0789c"));
			}

			public static class Facility
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("9f0aade4-5dc5-4d88-b350-15bd8fafed28"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Facility_fc282509
				{
					get;
				}

				= new FieldDescriptorID(new Guid("fc282509-8271-4580-9ff6-ee3366d5df70"));
			}

			public static class RoomOwnership
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("92517859-4d32-471f-93d6-2a41de0d94ce"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Team
				{
					get;
				}

				= new FieldDescriptorID(new Guid("371b8e3c-1c5c-4342-81fe-2a8d60d617c5"));
				public static FieldDescriptorID Owner
				{
					get;
				}

				= new FieldDescriptorID(new Guid("8ca723ed-6040-4d97-8ba6-ed05d1546071"));
			}

			public static class RackInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("05207b85-724c-4b96-8e50-e8419bb32696"))
				{ ModuleId = "(slc)facility_management" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("3bcf5f23-8178-4058-8300-6c32c1bdf066"));
				public static FieldDescriptorID Model
				{
					get;
				}

				= new FieldDescriptorID(new Guid("fb2f13e8-36c0-45ec-a80e-2ccf40a1b3a3"));
				public static FieldDescriptorID Position
				{
					get;
				}

				= new FieldDescriptorID(new Guid("c499cb89-b20d-41d5-8aa9-4ffdd98d6cda"));
				public static FieldDescriptorID Width
				{
					get;
				}

				= new FieldDescriptorID(new Guid("cd193a69-ddd4-4a53-84a5-3456f80bc00c"));
				public static FieldDescriptorID Depth
				{
					get;
				}

				= new FieldDescriptorID(new Guid("32ec429c-8099-44f6-981d-9d30bd7fe0ca"));
				public static FieldDescriptorID Height
				{
					get;
				}

				= new FieldDescriptorID(new Guid("c4bc0a18-05c8-4c64-8c47-c173db032fa8"));
				public static FieldDescriptorID Description
				{
					get;
				}

				= new FieldDescriptorID(new Guid("0fce02b2-8ddc-4518-900e-8f1fae8ec542"));
				public static FieldDescriptorID Bookable
				{
					get;
				}

				= new FieldDescriptorID(new Guid("7369d14b-12e4-4208-a3e9-6222e086d9ce"));
				public static FieldDescriptorID CoolingFlow
				{
					get;
				}

				= new FieldDescriptorID(new Guid("94fddd93-29a6-4ae3-a8a6-7ffe2e94a1ab"));
				public static FieldDescriptorID X
				{
					get;
				}

				= new FieldDescriptorID(new Guid("ebb91116-270e-4350-9829-b921e86e9dc0"));
				public static FieldDescriptorID Y
				{
					get;
				}

				= new FieldDescriptorID(new Guid("0f1b519b-7c8d-452e-b3f6-1b05e84f9a65"));
				public static FieldDescriptorID Label
				{
					get;
				}

				= new FieldDescriptorID(new Guid("587351f7-0e2f-46d5-95d6-ef4ad5ffeb47"));
				public static FieldDescriptorID Color
				{
					get;
				}

				= new FieldDescriptorID(new Guid("07a59549-3be3-4901-974c-6f81c5502c40"));
				public static FieldDescriptorID PlacementOrientation
				{
					get;
				}

				= new FieldDescriptorID(new Guid("d799109e-18af-47c2-8765-82231df2dee5"));
				public static FieldDescriptorID RackID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("5a337cca-f388-4018-b39f-55e042a2e001"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Room
			{
				get;
			}

			= new DomDefinitionId(new Guid("a09ef2ae-78b6-435a-a5b6-f4b91b3ba14f"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Desk
			{
				get;
			}

			= new DomDefinitionId(new Guid("9af0e791-b171-4b92-86e7-79dbb8282f66"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Site
			{
				get;
			}

			= new DomDefinitionId(new Guid("5320914d-ffec-486a-9950-b69276b6c13f"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Facility
			{
				get;
			}

			= new DomDefinitionId(new Guid("dab0442b-b092-4dbf-a249-19dd421c69db"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Row
			{
				get;
			}

			= new DomDefinitionId(new Guid("29eef06e-ed52-4a26-95da-fd35cc4433df"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Zone
			{
				get;
			}

			= new DomDefinitionId(new Guid("4576240b-b3da-4739-89d1-c3c5e79a26d9"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId FacilityManagerAppSettings
			{
				get;
			}

			= new DomDefinitionId(new Guid("a07a6f21-b919-4903-ae76-c8442fd97f54"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Rack
			{
				get;
			}

			= new DomDefinitionId(new Guid("c7877685-0295-40b2-acb1-9aea5d7d9c21"))
			{ ModuleId = "(slc)facility_management" };
			public static DomDefinitionId Floor
			{
				get;
			}

			= new DomDefinitionId(new Guid("9bbb18c2-8284-4e12-a1d1-f2ebb7e2c1fc"))
			{ ModuleId = "(slc)facility_management" };
		}

		public static class Behaviors
		{
			public static class Room_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("cce8f754-26c5-4e5e-97fb-0e474afbec5c"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "4e2df2d6-7e92-46e4-be9b-66dd8bb7e827";
					public const string Active = "84baed08-3f7b-4cd7-9428-79b1263f6a73";
					public const string Deprecated = "f5d5027c-3281-44d7-aeb5-fe55fd5cf1bd";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Active:
								return Active;
							case StatusesEnum.Deprecated:
								return Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Active:
								return StatusesEnum.Active;
							case Deprecated:
								return StatusesEnum.Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Active,
					Deprecated
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Facility_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("843615ba-3f5d-46a7-91d8-504ddabcdad4"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "bbdcf703-d257-45f9-8d62-13ec7adc37b3";
					public const string Deprecated = "43d4cef9-3d6a-41cf-83dd-5c671efde61d";
					public const string Active = "0350936d-9947-43ba-b4fe-362d375f4a85";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Deprecated:
								return Deprecated;
							case StatusesEnum.Active:
								return Active;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Deprecated:
								return StatusesEnum.Deprecated;
							case Active:
								return StatusesEnum.Active;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Deprecated,
					Active
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Site_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("903a2ba4-5467-4e8e-b728-8f3cd1ff0e72"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "bbdcf703-d257-45f9-8d62-13ec7adc37b3";
					public const string Deprecated = "43d4cef9-3d6a-41cf-83dd-5c671efde61d";
					public const string Active = "0350936d-9947-43ba-b4fe-362d375f4a85";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Deprecated:
								return Deprecated;
							case StatusesEnum.Active:
								return Active;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Deprecated:
								return StatusesEnum.Deprecated;
							case Active:
								return StatusesEnum.Active;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Deprecated,
					Active
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Desk_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("fa64f66c-35a8-4b32-8a68-0b0b1341886d"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "615ec505-7cb6-4fde-9e80-e85312a4ddd4";
					public const string Active = "404c20a0-26ec-4c06-a1cd-50d0246b426d";
					public const string Deprecated = "07efb53a-5b44-45e3-be03-5e2eafe88d8c";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Active:
								return Active;
							case StatusesEnum.Deprecated:
								return Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Active:
								return StatusesEnum.Active;
							case Deprecated:
								return StatusesEnum.Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Active,
					Deprecated
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Zone_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("98f2c20b-c4a6-4297-9d57-291915d298c5"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "08607107-27f9-4eb8-8009-8f7b8661cc03";
					public const string Active = "471625e5-4603-433a-8218-9e61a0de6231";
					public const string Deprecated = "538b8fc7-cedb-4f35-9728-57d17f813967";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Active:
								return Active;
							case StatusesEnum.Deprecated:
								return Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Active:
								return StatusesEnum.Active;
							case Deprecated:
								return StatusesEnum.Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Active,
					Deprecated
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Row_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("c620b4a2-2139-4f15-ac6f-c8235f669296"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "59a7afbd-47ad-4628-add3-d09c4c77e931";
					public const string Active = "170a16ff-15ea-44e0-a54c-f73fa4f37a5e";
					public const string Deprecated = "6f874cbb-71ab-4f8e-b1a4-25a52299278f";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Active:
								return Active;
							case StatusesEnum.Deprecated:
								return Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Active:
								return StatusesEnum.Active;
							case Deprecated:
								return StatusesEnum.Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Active,
					Deprecated
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Floor_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("558627ea-71eb-4ac6-a655-dedce737649d"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "a9227926-67f8-4f64-97bc-bcce855c267a";
					public const string Active = "4b7a6778-1861-4d1f-b020-633a450beb44";
					public const string Deprecated = "56eded1e-32d0-4109-82b2-d07eed8380c1";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Active:
								return Active;
							case StatusesEnum.Deprecated:
								return Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Active:
								return StatusesEnum.Active;
							case Deprecated:
								return StatusesEnum.Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Active,
					Deprecated
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}

			public static class Rack_Behaviour
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("4139c312-2b0f-40f3-b875-26cf5066b705"))
				{ ModuleId = "(slc)facility_management" };
				public static class Statuses
				{
					public const string Draft = "4ec366ed-6337-4f17-a1b3-f03b1b0b93cd";
					public const string Active = "5abfe850-851c-4abb-bf5d-0dc00a61c989";
					public const string Deprecated = "5cb06723-8588-421b-9373-f83d86a88161";
					public static string ToValue(StatusesEnum @enum)
					{
						switch (@enum)
						{
							case StatusesEnum.Draft:
								return Draft;
							case StatusesEnum.Active:
								return Active;
							case StatusesEnum.Deprecated:
								return Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static StatusesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft:
								return StatusesEnum.Draft;
							case Active:
								return StatusesEnum.Active;
							case Deprecated:
								return StatusesEnum.Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum StatusesEnum
				{
					Draft,
					Active,
					Deprecated
				}

				public static class Transitions
				{
					public const string Draft_Active = "draft_active";
					public const string Active_Deprecated = "active_deprecated";
					public static string ToValue(TransitionsEnum @enum)
					{
						switch (@enum)
						{
							case TransitionsEnum.Draft_Active:
								return Draft_Active;
							case TransitionsEnum.Active_Deprecated:
								return Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static TransitionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Draft_Active:
								return TransitionsEnum.Draft_Active;
							case Active_Deprecated:
								return TransitionsEnum.Active_Deprecated;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum TransitionsEnum
				{
					Draft_Active,
					Active_Deprecated
				}

				public static class Actions
				{
					public const string Confirm = "confirm";
					public const string Archive = "archive";
					public static string ToValue(ActionsEnum @enum)
					{
						switch (@enum)
						{
							case ActionsEnum.Confirm:
								return Confirm;
							case ActionsEnum.Archive:
								return Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ActionsEnum ToEnum(string s)
					{
						switch (s)
						{
							case Confirm:
								return ActionsEnum.Confirm;
							case Archive:
								return ActionsEnum.Archive;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ActionsEnum
				{
					Confirm,
					Archive
				}
			}
		}
	}
}
