//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGen package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.PlanAndBuild.Models
{
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.PlanAndBuild.Models;

    using SLDataGateway.API.Types.Querying;

    using System;
    using System.Collections.Generic;

    internal sealed partial class JobTypeDomRepository_Middleware : Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType>
    {
        private readonly Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> _inner;
        private readonly IMiddlewareMarker<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> _middleware;

        public JobTypeDomRepository_Middleware(Skyline.DataMiner.SDM.IBulkRepository<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> inner, IMiddlewareMarker<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
        {
            _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            _middleware = middleware;
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType>> ReadPaged(FilterElement<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> filter)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnReadPaged(filter, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType>> ReadPaged(IQuery<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> query)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnReadPaged(query, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType>> ReadPaged(FilterElement<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> filter, int pageSize)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter, pageSize);
            }
        }

        public IEnumerable<IPagedResult<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType>> ReadPaged(IQuery<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> query, int pageSize)
        {
            if (_middleware is IPageableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query, pageSize);
            }
        }

        public IEnumerable<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> Read(FilterElement<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> filter)
        {
            if (_middleware is IReadableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnRead(filter, _inner.Read);
            }
            else
            {
                return _inner.Read(filter);
            }
        }

        public IEnumerable<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> Read(IQuery<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> query)
        {
            if (_middleware is IReadableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnRead(query, _inner.Read);
            }
            else
            {
                return _inner.Read(query);
            }
        }

        public long Count(FilterElement<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> filter)
        {
            if (_middleware is ICountableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnCount(filter, _inner.Count);
            }
            else
            {
                return _inner.Count(filter);
            }
        }

        public long Count(IQuery<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> query)
        {
            if (_middleware is ICountableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnCount(query, _inner.Count);
            }
            else
            {
                return _inner.Count(query);
            }
        }

        public IReadOnlyCollection<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> Create(IEnumerable<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> oToCreate)
        {
            if (_middleware is IBulkCreatableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType Create(Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType oToCreate)
        {
            if (_middleware is ICreatableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public IReadOnlyCollection<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> Update(IEnumerable<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> oToUpdate)
        {
            if (_middleware is IBulkUpdatableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType Update(Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType oToUpdate)
        {
            if (_middleware is IUpdatableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public void Delete(IEnumerable<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> oToDelete)
        {
            if (_middleware is IBulkDeletableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }

        public void Delete(Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType oToDelete)
        {
            if (_middleware is IDeletableMiddleware<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }
        public System.Collections.Generic.IReadOnlyCollection<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> CreateOrUpdate(System.Collections.Generic.IEnumerable<Skyline.DataMiner.SDM.PlanAndBuild.Models.JobType> oToCreateOrUpdate)
        {
            return _inner.CreateOrUpdate(oToCreateOrUpdate);
        }

    }
}
