//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.FacilityManagement.Models
{
    using System;

    using SharedMappers.DomIds;

    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    //[SdmDomMapper]
    internal static class DeskDomMapper
    {
        internal const string ModuleId = SlcFacility_Management.ModuleId;
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(SlcFacility_Management.Definitions.Desk.Id)
        {ModuleId = ModuleId};
        internal static class DeskInformation
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SlcFacility_Management.Sections.DeskInformation.Id.Id)
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Name = SlcFacility_Management.Sections.DeskInformation.Name;
            internal static FieldDescriptorID Plan = SlcFacility_Management.Sections.DeskInformation.Plan;
            internal static FieldDescriptorID Description = SlcFacility_Management.Sections.DeskInformation.Description;
            internal static FieldDescriptorID DeskID = SlcFacility_Management.Sections.DeskInformation.DeskID;
        }

        internal static class RoomFk
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SlcFacility_Management.Sections.Room.Id.Id)
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Room = SlcFacility_Management.Sections.Room.Room_8d904f8d;
        }

        internal static class Resource
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SlcFacility_Management.Sections.Resource.Id.Id)
            {ModuleId = ModuleId};
            internal static FieldDescriptorID ResourceId = SlcFacility_Management.Sections.Resource.LinkedResource;
        }
    }
}
