//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGen package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.PlanAndBuild.Models
{
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.PlanAndBuild.Models;

    using SLDataGateway.API.Types.Querying;

    using System;
    using System.Collections.Generic;

    internal sealed partial class PlanAndBuildAppSettingsDomRepository_Middleware : IBulkRepository<PlanAndBuild.Models.PlanAndBuildAppSettings>
    {
        private readonly IBulkRepository<PlanAndBuild.Models.PlanAndBuildAppSettings> _inner;
        private readonly IMiddlewareMarker<PlanAndBuild.Models.PlanAndBuildAppSettings> _middleware;

        public PlanAndBuildAppSettingsDomRepository_Middleware(IBulkRepository<PlanAndBuild.Models.PlanAndBuildAppSettings> inner, IMiddlewareMarker<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
        {
            _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            _middleware = middleware;
        }

        public IEnumerable<IPagedResult<PlanAndBuild.Models.PlanAndBuildAppSettings>> ReadPaged(FilterElement<PlanAndBuild.Models.PlanAndBuildAppSettings> filter)
        {
            if (_middleware is IPageableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnReadPaged(filter, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter);
            }
        }

        public IEnumerable<IPagedResult<PlanAndBuild.Models.PlanAndBuildAppSettings>> ReadPaged(IQuery<PlanAndBuild.Models.PlanAndBuildAppSettings> query)
        {
            if (_middleware is IPageableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnReadPaged(query, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query);
            }
        }

        public IEnumerable<IPagedResult<PlanAndBuild.Models.PlanAndBuildAppSettings>> ReadPaged(FilterElement<PlanAndBuild.Models.PlanAndBuildAppSettings> filter, int pageSize)
        {
            if (_middleware is IPageableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter, pageSize);
            }
        }

        public IEnumerable<IPagedResult<PlanAndBuild.Models.PlanAndBuildAppSettings>> ReadPaged(IQuery<PlanAndBuild.Models.PlanAndBuildAppSettings> query, int pageSize)
        {
            if (_middleware is IPageableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query, pageSize);
            }
        }

        public IEnumerable<PlanAndBuild.Models.PlanAndBuildAppSettings> Read(FilterElement<PlanAndBuild.Models.PlanAndBuildAppSettings> filter)
        {
            if (_middleware is IReadableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnRead(filter, _inner.Read);
            }
            else
            {
                return _inner.Read(filter);
            }
        }

        public IEnumerable<PlanAndBuild.Models.PlanAndBuildAppSettings> Read(IQuery<PlanAndBuild.Models.PlanAndBuildAppSettings> query)
        {
            if (_middleware is IReadableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnRead(query, _inner.Read);
            }
            else
            {
                return _inner.Read(query);
            }
        }

        public long Count(FilterElement<PlanAndBuild.Models.PlanAndBuildAppSettings> filter)
        {
            if (_middleware is ICountableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnCount(filter, _inner.Count);
            }
            else
            {
                return _inner.Count(filter);
            }
        }

        public long Count(IQuery<PlanAndBuild.Models.PlanAndBuildAppSettings> query)
        {
            if (_middleware is ICountableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnCount(query, _inner.Count);
            }
            else
            {
                return _inner.Count(query);
            }
        }

        public IReadOnlyCollection<PlanAndBuild.Models.PlanAndBuildAppSettings> Create(IEnumerable<PlanAndBuild.Models.PlanAndBuildAppSettings> oToCreate)
        {
            if (_middleware is IBulkCreatableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public PlanAndBuild.Models.PlanAndBuildAppSettings Create(PlanAndBuild.Models.PlanAndBuildAppSettings oToCreate)
        {
            if (_middleware is ICreatableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public IReadOnlyCollection<PlanAndBuild.Models.PlanAndBuildAppSettings> Update(IEnumerable<PlanAndBuild.Models.PlanAndBuildAppSettings> oToUpdate)
        {
            if (_middleware is IBulkUpdatableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public PlanAndBuild.Models.PlanAndBuildAppSettings Update(PlanAndBuild.Models.PlanAndBuildAppSettings oToUpdate)
        {
            if (_middleware is IUpdatableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public void Delete(IEnumerable<PlanAndBuild.Models.PlanAndBuildAppSettings> oToDelete)
        {
            if (_middleware is IBulkDeletableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }

        public void Delete(PlanAndBuild.Models.PlanAndBuildAppSettings oToDelete)
        {
            if (_middleware is IDeletableMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }
        public System.Collections.Generic.IReadOnlyCollection<PlanAndBuild.Models.PlanAndBuildAppSettings> CreateOrUpdate(System.Collections.Generic.IEnumerable<PlanAndBuild.Models.PlanAndBuildAppSettings> oToCreateOrUpdate)
        {
                if (_middleware is IBulkRepositoryMiddleware<PlanAndBuild.Models.PlanAndBuildAppSettings> middleware)
                {
                    return middleware.OnCreateOrUpdate(oToCreateOrUpdate, _inner.CreateOrUpdate);
                }
                else
                {
                    return _inner.CreateOrUpdate(oToCreateOrUpdate);
                }
        }

    }
}
