<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Skyline.DataMiner.SDM.FacilityManagement.Common</AssemblyName>
    <RootNamespace>Skyline.DataMiner.SDM.FacilityManagement.Common</RootNamespace>
    <PackageVersion>1.0.1</PackageVersion>
    <Version>1.0.1</Version>
    <PackageTags>Skyline;DataMiner</PackageTags>
    <PackageProjectUrl>https://skyline.be</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageIcon>Icon.png</PackageIcon>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>SkylineCommunications</Authors>
    <Company>Skyline Communications</Company>
    <Description>Standard API for Facility Management operations in DataMiner</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\SharedValidation\facilitymanagement\models\RackCapacity.cs" Link="RackCapacity.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="nuget\Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Skyline.DataMiner.SDM" />
    <PackageReference Include="Skyline.DataMiner.SDM.Linq" />
    <PackageReference Include="Skyline.DataMiner.Utils.DOM" />
    <PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>
  
  <Import Project="..\SharedMappers\SharedMappers.projitems" Label="Shared" />
  
  <Import Project="..\SharedValidation\SharedValidation.projitems" Label="Shared" />
</Project>
