//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Skyline.DataMiner.Net;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Apps.Sections.Sections;
    using Skyline.DataMiner.Net.Helper;
    using Skyline.DataMiner.Net.ManagerStore;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Net.SubscriptionFilters;
    using Skyline.DataMiner.SDM;

    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    internal partial class ConnectionDomRepository : IBulkRepository<Connection>
    {
        private readonly IConnection connection;
        private readonly DomHelper helper;
        public ConnectionDomRepository(IConnection connection)
        {
            this.connection = connection;
            this.helper = new DomHelper(connection.HandleMessages, AssetManagement.Models.ConnectionDomMapper.ModuleId);
        }

        public Connection Create(Connection createObject)
        {
            if (createObject is null)
            {
                throw new ArgumentNullException(nameof(createObject));
            }

            var instance = ToInstance(createObject);
            instance = helper.DomInstances.Create(instance);
            return FromInstance(instance);
        }

        public IReadOnlyCollection<Connection> Create(IEnumerable<Connection> createObjects)
        {
            if (createObjects is null || !createObjects.Any())
            {
                return Array.Empty<Connection>();
            }

            // Check if some of the objects already exist
            var existing = new HashSet<string>();
            foreach (var batch in createObjects.Batch(500))
            {
                existing.UnionWith(Read(new ORFilterElement<Connection>(batch.Select(obj => ConnectionExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
            }

            // Create the remainder
            var SuccessfulItems = new List<Connection>();
            var failures = new Dictionary<string, Exception>();
            var objects = createObjects.Where(obj => !existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
            foreach (var batch in createObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    SuccessfulItems.Add(FromInstance(success));
                }
            }

            // If everything went fine, return the successful creations
            if (!existing.Any() && !failures.Any())
            {
                return SuccessfulItems;
            }

            // Otherwise, build and throw an exception
            var exceptionBuilder = new SdmBulkCrudException<Connection>.Builder();
            foreach (var obj in createObjects)
            {
                if (existing.Contains(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, new SdmCrudException<Connection>(obj, $"Could not create Connection with guid: '{obj.Identifier}', it already exists."));
                    continue;
                }

                if (failures.ContainsKey(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
                    continue;
                }

                exceptionBuilder.AddSuccessful(obj);
            }

            throw exceptionBuilder.Build();
        }

        public IReadOnlyCollection<Connection> CreateOrUpdate(IEnumerable<Connection> items)
        {
            if (items is null || !items.Any())
            {
                return Array.Empty<Connection>();
            }

            var successful = new List<Connection>();
            var exceptionBuilder = new SdmBulkCrudException<Connection>.Builder();
            var objects = items.ToDictionary(obj => obj.Identifier);
            foreach (var batch in items.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    var item = FromInstance(success);
                    exceptionBuilder.AddSuccessful(item);
                    successful.Add(item);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successful;
        }

        public long Count(FilterElement<Connection> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            var domFilter = TranslateFullFilter(filter);
            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(AssetManagement.Models.ConnectionDomMapper.DomDefinitionId.Id));
            return helper.DomInstances.Count(domFilter);
        }

        public long Count(IQuery<Connection> query)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            var domFilter = TranslateFullFilter(query.Filter);
            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(AssetManagement.Models.ConnectionDomMapper.DomDefinitionId.Id));
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            return helper.DomInstances.Count(domQuery);
        }

        public IEnumerable<Connection> Read(FilterElement<Connection> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            var domFilter = TranslateFullFilter(filter);
            return Read(domFilter);
        }

        public IEnumerable<Connection> Read(IQuery<Connection> query)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            var domFilter = TranslateFullFilter(query.Filter);
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            return Read(domQuery);
        }

        public IEnumerable<IPagedResult<Connection>> ReadPaged(FilterElement<Connection> filter)
        {
            return ReadPaged(filter, 500);
        }

        public IEnumerable<IPagedResult<Connection>> ReadPaged(FilterElement<Connection> filter, int pageSize)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            if (pageSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
            }

            var domFilter = TranslateFullFilter(filter);
            var paging = ReadPaged(domFilter, pageSize).GetEnumerator();
            var moveNext = paging.MoveNext();
            var i = 0;
            while (moveNext)
            {
                var page = paging.Current.ToList();
                moveNext = paging.MoveNext();
                var result = new PagedResult<Connection>(page, i, pageSize, moveNext);
                yield return result;
                i++;
            }
        }

        public IEnumerable<IPagedResult<Connection>> ReadPaged(IQuery<Connection> query)
        {
            return ReadPaged(query, 500);
        }

        public IEnumerable<IPagedResult<Connection>> ReadPaged(IQuery<Connection> query, int pageSize)
        {
            if (query is null)
            {
                throw new ArgumentNullException(nameof(query));
            }

            if (pageSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
            }

            var domFilter = TranslateFullFilter(query.Filter);
            var domOrder = TranslateFullOrderBy(query.Order);
            var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
            var paging = ReadPaged(domQuery, pageSize).GetEnumerator();
            var moveNext = paging.MoveNext();
            var i = 0;
            while (moveNext)
            {
                var page = paging.Current.ToList();
                moveNext = paging.MoveNext();
                var result = new PagedResult<Connection>(page, i, pageSize, moveNext);
                yield return result;
                i++;
            }
        }

        public Connection Update(Connection updateObject)
        {
            if (updateObject is null)
            {
                throw new ArgumentNullException(nameof(updateObject));
            }

            var instance = ToInstance(updateObject);
            instance = helper.DomInstances.Update(instance);
            return FromInstance(instance);
        }

        public IReadOnlyCollection<Connection> Update(IEnumerable<Connection> updateObjects)
        {
            if (updateObjects is null || !updateObjects.Any())
            {
                return Array.Empty<Connection>();
            }

            // Check if which objects already exist
            var existing = new HashSet<string>();
            foreach (var batch in updateObjects.Batch(500))
            {
                existing.UnionWith(Read(new ORFilterElement<Connection>(batch.Select(obj => ConnectionExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
            }

            // Update the existing objects
            var successfulItems = new List<Connection>();
            var failures = new Dictionary<string, Exception>();
            var objects = updateObjects.Where(obj => existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
            foreach (var batch in updateObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulItems)
                {
                    successfulItems.Add(FromInstance(success));
                }
            }

            // Check for failures and build exception if needed
            var exceptionBuilder = new SdmBulkCrudException<Connection>.Builder();
            foreach (var obj in updateObjects)
            {
                if (!existing.Contains(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, new SdmCrudException<Connection>(obj, "Could not update a non existing Connection"));
                    continue;
                }

                if (failures.ContainsKey(obj.Identifier))
                {
                    exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
                    continue;
                }

                exceptionBuilder.AddSuccessful(obj);
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }

            return successfulItems;
        }

        public void Delete(Connection deleteObject)
        {
            if (deleteObject is null)
            {
                throw new ArgumentNullException(nameof(deleteObject));
            }

            var instance = ToInstance(deleteObject);
            helper.DomInstances.Delete(instance);
        }

        public void Delete(IEnumerable<Connection> deleteObjects)
        {
            if (deleteObjects is null || !deleteObjects.Any())
            {
                return;
            }

            var exceptionBuilder = new SdmBulkCrudException<Connection>.Builder();
            var objects = deleteObjects.ToDictionary(obj => obj.Identifier);
            foreach (var batch in deleteObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
            {
                helper.DomInstances.TryDelete(batch.ToList(), out var result);
                foreach (var failure in result.UnsuccessfulIds)
                {
                    exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
                }

                foreach (var success in result.SuccessfulIds)
                {
                    exceptionBuilder.AddSuccessful(objects[success.Id.ToString()]);
                }
            }

            if (exceptionBuilder.HasFailure)
            {
                throw exceptionBuilder.Build();
            }
        }

        private IEnumerable<Connection> Read(FilterElement<DomInstance> domFilter)
        {
            if (domFilter is null)
            {
                throw new ArgumentNullException(nameof(domFilter));
            }

            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(AssetManagement.Models.ConnectionDomMapper.DomDefinitionId.Id));
            var domInstances = helper.DomInstances.Read(domFilter);
            return domInstances.Select(FromInstance);
        }

        private IEnumerable<Connection> Read(IQuery<DomInstance> domQuery)
        {
            if (domQuery is null)
            {
                throw new ArgumentNullException(nameof(domQuery));
            }

            var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(AssetManagement.Models.ConnectionDomMapper.DomDefinitionId.Id));
            domQuery = domQuery.WithFilter(domFilter);
            var domInstances = helper.DomInstances.Read(domQuery);
            return domInstances.Select(FromInstance);
        }

        private IEnumerable<IEnumerable<Connection>> ReadPaged(FilterElement<DomInstance> domFilter, int pageSize)
        {
            if (domFilter is null)
            {
                throw new ArgumentNullException(nameof(domFilter));
            }

            domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(AssetManagement.Models.ConnectionDomMapper.DomDefinitionId.Id));
            var pagingHelper = helper.DomInstances.PreparePaging(domFilter, pageSize);
            while (pagingHelper.MoveToNextPage())
            {
                yield return pagingHelper.GetCurrentPage().Select(FromInstance);
            }
        }

        private IEnumerable<IEnumerable<Connection>> ReadPaged(IQuery<DomInstance> domQuery, int pageSize)
        {
            if (domQuery is null)
            {
                throw new ArgumentNullException(nameof(domQuery));
            }

            var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(AssetManagement.Models.ConnectionDomMapper.DomDefinitionId.Id));
            domQuery = domQuery.WithFilter(domFilter);
            var pagingHelper = helper.DomInstances.PreparePaging(domQuery, pageSize);
            while (pagingHelper.MoveToNextPage())
            {
                yield return pagingHelper.GetCurrentPage().Select(FromInstance);
            }
        }

        private FilterElement<DomInstance> TranslateFullFilter(FilterElement<Connection> filter)
        {
            if (filter is null)
            {
                throw new ArgumentNullException(nameof(filter));
            }

            FilterElement<DomInstance> translated;
            if (filter is ANDFilterElement<Connection> and)
            {
                translated = new ANDFilterElement<DomInstance>(and.subFilters.Select(TranslateFullFilter).ToArray());
            }
            else if (filter is ORFilterElement<Connection> or)
            {
                translated = new ORFilterElement<DomInstance>(or.subFilters.Select(TranslateFullFilter).ToArray());
            }
            else if (filter is NOTFilterElement<Connection> not)
            {
                translated = new NOTFilterElement<DomInstance>(TranslateFullFilter(not));
            }
            else if (filter is TRUEFilterElement<Connection>)
            {
                translated = new TRUEFilterElement<DomInstance>();
            }
            else if (filter is FALSEFilterElement<Connection>)
            {
                translated = new FALSEFilterElement<DomInstance>();
            }
            else if (filter is ManagedFilterIdentifier managedFilter)
            {
                translated = TranslateFilter(managedFilter);
            }
            else
            {
                throw new NotSupportedException($"Unsupported filter: {filter}");
            }

            return translated;
        }

        private IOrderBy TranslateFullOrderBy(IOrderBy order)
        {
            if (order is null)
            {
                throw new ArgumentNullException(nameof(order));
            }

            var translatedElements = new List<IOrderByElement>();
            foreach (var orderByElement in order.Elements)
            {
                var translated = TranslateOrderBy(orderByElement);
                translatedElements.Add(translated);
            }

            return new OrderBy(translatedElements);
        }

        private FilterElement<DomInstance> TranslateFilter(ManagedFilterIdentifier managedFilter)
        {
            if (managedFilter is null)
            {
                throw new ArgumentNullException(nameof(managedFilter));
            }

            var fieldName = managedFilter.getFieldName().fieldName;
            var comparer = managedFilter.getComparer();
            var value = managedFilter.getValue();
            var translated = CreateFilter(fieldName, comparer, value);
            return translated;
        }

        private IOrderByElement TranslateOrderBy(IOrderByElement orderByElement)
        {
            if (orderByElement is null)
            {
                throw new ArgumentNullException(nameof(orderByElement));
            }

            var fieldName = orderByElement.Exposer.fieldName;
            var sortOrder = orderByElement.SortOrder;
            var naturalSort = orderByElement.Options.NaturalSort;
            var translated = CreateOrderBy(fieldName, sortOrder, naturalSort);
            return translated;
        }

        private Connection FromInstance(DomInstance instance)
        {
            var obj = new Connection
            {
                Identifier = instance.ID.Id.ToString()
            };
            var _connectionpropertiesSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.SectionDefinitionId));
            if (_connectionpropertiesSection != default)
            {
                obj.ConnectionPropertiesSectionId = _connectionpropertiesSection.ID.Id;
                var _notes = _connectionpropertiesSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Notes);
                if (_notes != null)
                {
                    obj.Notes = _notes.Value;
                }

                var _description = _connectionpropertiesSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Description);
                if (_description != null)
                {
                    obj.Description = _description.Value;
                }

                var _connectiontype = _connectionpropertiesSection.GetValue<int>(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.ConnectionType);
                if (_connectiontype != null)
                {
                    obj.ConnectionType = (SharedMappers.DomIds.SlcAsset_Management.Enums.ConnectionType)_connectiontype.Value;
                }
            }

            var _cableInformationSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(AssetManagement.Models.ConnectionDomMapper.CableInformation.SectionDefinitionId));
            if (_cableInformationSection != default)
            {
                obj.CableInformationSectionId = _cableInformationSection.ID.Id;
                var _cabletype = _cableInformationSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableType);
                if (_cabletype != null)
                {
                    obj.CableType = new SdmObjectReference<AssetManagement.Models.CableType>(Convert.ToString(_cabletype.Value));
                }

                var _cablelength = _cableInformationSection.GetValue<double>(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableLength);
                if (_cablelength != null)
                {
                    obj.CableLength = _cablelength.Value;
                }
            }

            var _sourceSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(AssetManagement.Models.ConnectionDomMapper.Source.SectionDefinitionId));
            if (_sourceSection != default)
            {
                obj.Source = new AssetManagement.Models.SourceInfo();
                ((Skyline.DataMiner.Utils.InfraOps.Common.Fields.ISectionTrackable)obj.Source).SectionId = _sourceSection.ID.Id;
                var _sourcecabletag = _sourceSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.Source.CableTag);
                if (_sourcecabletag != null)
                {
                    obj.Source.CableTag = _sourcecabletag.Value;
                }

                var _sourceport = _sourceSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.Source.Port);
                if (_sourceport != null)
                {
                    obj.Source.Port = System.Guid.Parse(Convert.ToString(_sourceport.Value));
                }

                var _sourceporttype = _sourceSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.Source.PortType);
                if (_sourceporttype != null)
                {
                    obj.Source.PortType = new SdmObjectReference<AssetManagement.Models.PortType>(Convert.ToString(_sourceporttype.Value));
                }
            }

            var _destinationSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(AssetManagement.Models.ConnectionDomMapper.Destination.SectionDefinitionId));
            if (_destinationSection != default)
            {
                obj.Destination = new AssetManagement.Models.DestinationInfo();
                ((Skyline.DataMiner.Utils.InfraOps.Common.Fields.ISectionTrackable)obj.Destination).SectionId = _destinationSection.ID.Id;
                var _destinationcabletag = _destinationSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.Destination.CableTag);
                if (_destinationcabletag != null)
                {
                    obj.Destination.CableTag = _destinationcabletag.Value;
                }

                var _destinationport = _destinationSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.Destination.Port);
                if (_destinationport != null)
                {
                    obj.Destination.Port = System.Guid.Parse(Convert.ToString(_destinationport.Value));
                }

                var _destinationporttype = _destinationSection.GetValue<string>(AssetManagement.Models.ConnectionDomMapper.Destination.PortType);
                if (_destinationporttype != null)
                {
                    obj.Destination.PortType = new SdmObjectReference<AssetManagement.Models.PortType>(Convert.ToString(_destinationporttype.Value));
                }
            }

            return obj;
        }

        private DomInstance ToInstance(Connection obj)
        {
            Guid id = default(Guid);
            if (!String.IsNullOrEmpty(obj.Identifier))
            {
                id = Guid.Parse(obj.Identifier);
            }
            else
            {
                id = Guid.NewGuid();
            }

            var instance = new DomInstance
            {
                DomDefinitionId = AssetManagement.Models.ConnectionDomMapper.DomDefinitionId,
                ID = new DomInstanceId(id)
                {
                    ModuleId = AssetManagement.Models.ConnectionDomMapper.ModuleId
                }
            };
            var _connectionproperties = new Section(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.SectionDefinitionId);
            if (obj.ConnectionPropertiesSectionId.HasValue)
            {
                _connectionproperties.ID = new SectionID(obj.ConnectionPropertiesSectionId.Value);
            }
            if (obj.Notes != default)
            {
                _connectionproperties.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Notes, Convert.ToString(obj.Notes));
            }

            if (obj.Description != default)
            {
                _connectionproperties.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Description, Convert.ToString(obj.Description));
            }

            if (obj.ConnectionType != default)
            {
                _connectionproperties.AddOrUpdateValue<int>(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.ConnectionType, (int)(obj.ConnectionType));
            }

            instance.Sections.Add(_connectionproperties);

            var _cableinformation = new Section(AssetManagement.Models.ConnectionDomMapper.CableInformation.SectionDefinitionId);
            if (obj.CableInformationSectionId.HasValue)
            {
                _cableinformation.ID = new SectionID(obj.CableInformationSectionId.Value);
            }
            if (obj.CableType != default)
            {
                _cableinformation.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableType, obj.CableType.Identifier);
            }

            if (obj.CableLength != default)
            {
                _cableinformation.AddOrUpdateValue<double>(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableLength, obj.CableLength.Value);
            }
            instance.Sections.Add(_cableinformation);

            if (obj.Source != null)
            {
                var _source = new Section(AssetManagement.Models.ConnectionDomMapper.Source.SectionDefinitionId);
                var _sourceSectionId = ((Skyline.DataMiner.Utils.InfraOps.Common.Fields.ISectionTrackable)obj.Source).SectionId;
                if (_sourceSectionId.HasValue)
                {
                    _source.ID = new SectionID(_sourceSectionId.Value);
                }
                if (obj.Source.CableTag != default)
                {
                    _source.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.Source.CableTag, Convert.ToString(obj.Source.CableTag));
                }

                if (obj.Source.Port != default)
                {
                    _source.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.Source.Port, Convert.ToString(obj.Source.Port));
                }

                if (obj.Source.PortType != default)
                {
                    _source.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.Source.PortType, obj.Source.PortType.Identifier);
                }

                instance.Sections.Add(_source);
            }

            if (obj.Destination != null)
            {
                var _destination = new Section(AssetManagement.Models.ConnectionDomMapper.Destination.SectionDefinitionId);
                var _destinationSectionId = ((Skyline.DataMiner.Utils.InfraOps.Common.Fields.ISectionTrackable)obj.Destination).SectionId;
                if (_destinationSectionId.HasValue)
                {
                    _destination.ID = new SectionID(_destinationSectionId.Value);
                }
                if (obj.Destination.CableTag != default)
                {
                    _destination.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.Destination.CableTag, Convert.ToString(obj.Destination.CableTag));
                }

                if (obj.Destination.Port != default)
                {
                    _destination.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.Destination.Port, Convert.ToString(obj.Destination.Port));
                }

                if (obj.Destination.PortType != default)
                {
                    _destination.AddOrUpdateValue<string>(AssetManagement.Models.ConnectionDomMapper.Destination.PortType, obj.Destination.PortType.Identifier);
                }

                instance.Sections.Add(_destination);
            }

            return instance;
        }

        private FilterElement<DomInstance> CreateFilter(string fieldName, Comparer comparer, object value)
        {
            switch (fieldName)
            {
                case "Identifier":
                    return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.Id, comparer, Guid.Parse((string)value));
                case "Notes":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Notes), comparer, (string)value);
                case "Description":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Description), comparer, (string)value);
                case "ConnectionType":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.ConnectionType), comparer, (int)(SharedMappers.DomIds.SlcAsset_Management.Enums.ConnectionType)value);
                case "CableType":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableType), comparer, SdmObjectReference<AssetManagement.Models.CableType>.Convert(value).Identifier);
                case "CableLength":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableLength), comparer, (double)value);
                case "Source.CableTag":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Source.CableTag), comparer, (string)value);
                case "Source.Port":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Source.Port), comparer, Convert.ToString((System.Guid)value));
                case "Source.PortType":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Source.PortType), comparer, SdmObjectReference<AssetManagement.Models.PortType>.Convert(value).Identifier);
                case "Destination.CableTag":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Destination.CableTag), comparer, (string)value);
                case "Destination.Port":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Destination.Port), comparer, Convert.ToString((System.Guid)value));
                case "Destination.PortType":
                    return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Destination.PortType), comparer, SdmObjectReference<AssetManagement.Models.PortType>.Convert(value).Identifier);
                default:
                    throw new NotImplementedException();
            }
        }

        private IOrderByElement CreateOrderBy(string fieldName, SortOrder sortOrder, bool naturalSort = false)
        {
            switch (fieldName)
            {
                case "Identifier":
                    return OrderByElementFactory.Create(DomInstanceExposers.Id, sortOrder, naturalSort);
                case "Notes":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Notes), sortOrder, naturalSort);
                case "Description":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.Description), sortOrder, naturalSort);
                case "ConnectionType":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.ConnectionProperties.ConnectionType), sortOrder, naturalSort);
                case "CableType":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableType), sortOrder, naturalSort);
                case "CableLength":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.CableInformation.CableLength), sortOrder, naturalSort);
                case "Source.CableTag":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Source.CableTag), sortOrder, naturalSort);
                case "Source.Port":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Source.Port), sortOrder, naturalSort);
                case "Source.PortType":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Source.PortType), sortOrder, naturalSort);
                case "Destination.CableTag":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Destination.CableTag), sortOrder, naturalSort);
                case "Destination.Port":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Destination.Port), sortOrder, naturalSort);
                case "Destination.PortType":
                    return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(AssetManagement.Models.ConnectionDomMapper.Destination.PortType), sortOrder, naturalSort);
                default:
                    throw new NotImplementedException();
            }
        }
    }
}