//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM
{
    using Skyline.DataMiner.SDM.Middleware;
    using Skyline.DataMiner.SDM.FacilityManagement.Models;
    using Skyline.DataMiner.SDM;

    public static class FacilityManagerAppSettingsDomRepository_Extensions
    {
        public static IBulkRepository<FacilityManagement.Models.FacilityManagerAppSettings> WithMiddleware(
            this IBulkRepository<FacilityManagement.Models.FacilityManagerAppSettings> repository,
            IMiddlewareMarker<FacilityManagement.Models.FacilityManagerAppSettings> middleware)
        {
            return new FacilityManagerAppSettingsDomRepository_Middleware(repository, middleware);
        }
    }
}
