//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
using Skyline.DataMiner.Net.Sections;
using Skyline.DataMiner.SDM;

namespace Skyline.DataMiner.SDM.InfraOpsProperties.Models
{
    [SdmDomMapper]
    public static class PropertyValuesDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.InfraopsProperties.ModuleId;
        internal static DomDefinitionId DomDefinitionId => SharedMappers.DomIds.InfraopsProperties.Definitions.PropertyValues;

        public static class PropertyValuesProperties
        {
            internal static SectionDefinitionID SectionDefinitionId => SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValueInfo.Id;

            public static readonly FieldDescriptorID LinkedObjectID = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValueInfo.LinkedObjectID;
            public static readonly FieldDescriptorID Scope = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValueInfo.Scope;
            public static readonly FieldDescriptorID SubID = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValueInfo.SubID;
        }

        public static class Values
        {
            internal static SectionDefinitionID SectionDefinitionId => SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValue.Id;

            public static readonly FieldDescriptorID PropertyName = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValue.PropertyName;
            public static readonly FieldDescriptorID Value = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValue.Value;
            public static readonly FieldDescriptorID PropertyId = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyValue.PropertyID;
        }
    }
}