//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
using Skyline.DataMiner.Net.Sections;
using Skyline.DataMiner.SDM;

namespace Skyline.DataMiner.SDM.InfraOpsProperties.Models
{
    [SdmDomMapper]
    public static class PropertyDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.InfraopsProperties.ModuleId;
        internal static DomDefinitionId DomDefinitionId => SharedMappers.DomIds.InfraopsProperties.Definitions.Property;

        public static class PropertyProperties
        {
            internal static SectionDefinitionID SectionDefinitionId => SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.Id;

            public static readonly FieldDescriptorID Name = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.Name;
            public static readonly FieldDescriptorID PropertyType = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.PropertyType;
            public static readonly FieldDescriptorID Scope = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.Scope;
            public static readonly FieldDescriptorID Default = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.Default;
            public static readonly FieldDescriptorID StringSizeLimit = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.StringSizeLimit;
            public static readonly FieldDescriptorID IsMultiLineString = SharedMappers.DomIds.InfraopsProperties.Sections.PropertyInfo.IsMultiLineString;
        }

        public static class Layout
        {
            internal static SectionDefinitionID SectionDefinitionId => SharedMappers.DomIds.InfraopsProperties.Sections.Layout.Id;

            public static readonly FieldDescriptorID SectionName = SharedMappers.DomIds.InfraopsProperties.Sections.Layout.SectionName;
            public static readonly FieldDescriptorID Order = SharedMappers.DomIds.InfraopsProperties.Sections.Layout.Order;
        }

        public static class Discreets
        {
            internal static SectionDefinitionID SectionDefinitionId => SharedMappers.DomIds.InfraopsProperties.Sections.Discrete.Id;

            public static readonly FieldDescriptorID Option = SharedMappers.DomIds.InfraopsProperties.Sections.Discrete.Option;
        }
    }
}