//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SharedMappers.DomIds
{
	using System;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class InfraopsProperties
	{
		public const string ModuleId = "(infraops)properties";
		public static class Enums
		{
			public static class Propertytype
			{
				public const string String = "string";
				public const string Discrete = "discrete";
				public const string Boolean = "boolean";
				public static string ToValue(PropertyTypeEnum @enum)
				{
					switch (@enum)
					{
						case PropertyTypeEnum.String:
							return String;
						case PropertyTypeEnum.Discrete:
							return Discrete;
						case PropertyTypeEnum.Boolean:
							return Boolean;
						default:
							throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
					}
				}

				public static PropertyTypeEnum ToEnum(string s)
				{
					switch (s)
					{
						case String:
							return PropertyTypeEnum.String;
						case Discrete:
							return PropertyTypeEnum.Discrete;
						case Boolean:
							return PropertyTypeEnum.Boolean;
						default:
							throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
					}
				}
			}

			public enum PropertyTypeEnum
			{
				String,
				Discrete,
				Boolean
			}
		}

		public static class Sections
		{
			public static class PropertyInfo
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("a99ddb61-78b5-42c5-939d-521cd6cdc0ef"))
				{ ModuleId = "(infraops)properties" };
				public static FieldDescriptorID Name
				{
					get;
				}

				= new FieldDescriptorID(new Guid("b84045d8-6eaa-405c-9b57-abd77c5952be"));
				public static FieldDescriptorID PropertyType
				{
					get;
				}

				= new FieldDescriptorID(new Guid("9936899d-9649-401c-b809-835ebb16b4d9"));
				public static FieldDescriptorID Scope
				{
					get;
				}

				= new FieldDescriptorID(new Guid("5ddb4403-4800-454d-a46a-d45f803a88df"));
				public static FieldDescriptorID Default
				{
					get;
				}

				= new FieldDescriptorID(new Guid("d0858913-71b9-4818-90a2-e4a4c2a232d8"));
				public static FieldDescriptorID StringSizeLimit
				{
					get;
				}

				= new FieldDescriptorID(new Guid("143b59e7-f576-47b5-a0f2-46f7591c324c"));
				public static FieldDescriptorID IsMultiLineString
				{
					get;
				}

				= new FieldDescriptorID(new Guid("d39ff167-7751-49e3-8053-86cc01716b61"));
			}

			public static class PropertyValueInfo
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("98c6c75e-855a-438a-b96a-ad14fafe1db7"))
				{ ModuleId = "(infraops)properties" };
				public static FieldDescriptorID LinkedObjectID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("03e6c268-eb10-465e-848e-ff1cda78aca8"));
				public static FieldDescriptorID Scope
				{
					get;
				}

				= new FieldDescriptorID(new Guid("1420fd59-e5f1-490d-9c39-702fceb15291"));
				public static FieldDescriptorID SubID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("c6949bcd-84ae-4c42-b687-1b26714c725c"));
			}

			public static class PropertyValue
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("3f0e4530-8569-4eb6-aac3-8e4306b5d3ff"))
				{ ModuleId = "(infraops)properties" };
				public static FieldDescriptorID PropertyName
				{
					get;
				}

				= new FieldDescriptorID(new Guid("17701cad-3394-4e4e-8f53-55b0d69d39ad"));
				public static FieldDescriptorID Value
				{
					get;
				}

				= new FieldDescriptorID(new Guid("ce77c7ac-f031-4937-9f6c-6b01ffb28efd"));
				public static FieldDescriptorID PropertyID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("37ddd69c-f08f-4d7a-b845-9db72653ffd6"));
			}

			public static class Layout
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("bd33a4c7-9e7b-44f5-9048-6737ab3191e2"))
				{ ModuleId = "(infraops)properties" };
				public static FieldDescriptorID SectionName
				{
					get;
				}

				= new FieldDescriptorID(new Guid("62802953-4384-400c-92e6-46eda4f872f6"));
				public static FieldDescriptorID Order
				{
					get;
				}

				= new FieldDescriptorID(new Guid("d397f123-8606-47bc-8471-d23c79d32cbd"));
			}

			public static class Discrete
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("3ca75450-2b4b-48df-a893-2ca712f521f7"))
				{ ModuleId = "(infraops)properties" };
				public static FieldDescriptorID Option
				{
					get;
				}

				= new FieldDescriptorID(new Guid("c9066d6b-2447-43b0-b8e4-367b5c378b0a"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId PropertyValues
			{
				get;
			}

			= new DomDefinitionId(new Guid("239ed807-3508-4f00-b950-6681cc25a332"))
			{ ModuleId = "(infraops)properties" };
			public static DomDefinitionId Property
			{
				get;
			}

			= new DomDefinitionId(new Guid("d7e4ecb9-dc79-496e-90c7-310b340a248b"))
			{ ModuleId = "(infraops)properties" };
		}

		public static class Behaviors
		{
		}
	}
}
