//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using Skyline.DataMiner.Net;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.Net.SubscriptionFilters;
	using Skyline.DataMiner.SDM;
	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	internal sealed partial class PowerPortDomRepository_Middleware : IBulkRepository<AssetManagement.Models.PowerPort>
	{
		private readonly IBulkRepository<AssetManagement.Models.PowerPort> _inner;
		private readonly IMiddlewareMarker<AssetManagement.Models.PowerPort> _middleware;

		public PowerPortDomRepository_Middleware(IBulkRepository<AssetManagement.Models.PowerPort> inner, IMiddlewareMarker<AssetManagement.Models.PowerPort> middleware)
		{
			_inner = inner ?? throw new ArgumentNullException(nameof(inner));
			_middleware = middleware;
		}

		public IEnumerable<IPagedResult<AssetManagement.Models.PowerPort>> ReadPaged(FilterElement<AssetManagement.Models.PowerPort> filter)
		{
			if (_middleware is IPageableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnReadPaged(filter, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(filter);
			}
		}

		public IEnumerable<IPagedResult<AssetManagement.Models.PowerPort>> ReadPaged(IQuery<AssetManagement.Models.PowerPort> query)
		{
			if (_middleware is IPageableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnReadPaged(query, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(query);
			}
		}

		public IEnumerable<IPagedResult<AssetManagement.Models.PowerPort>> ReadPaged(FilterElement<AssetManagement.Models.PowerPort> filter, int pageSize)
		{
			if (_middleware is IPageableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(filter, pageSize);
			}
		}

		public IEnumerable<IPagedResult<AssetManagement.Models.PowerPort>> ReadPaged(IQuery<AssetManagement.Models.PowerPort> query, int pageSize)
		{
			if (_middleware is IPageableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
			}
			else
			{
				return _inner.ReadPaged(query, pageSize);
			}
		}

		public IEnumerable<AssetManagement.Models.PowerPort> Read(FilterElement<AssetManagement.Models.PowerPort> filter)
		{
			if (_middleware is IReadableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnRead(filter, _inner.Read);
			}
			else
			{
				return _inner.Read(filter);
			}
		}

		public IEnumerable<AssetManagement.Models.PowerPort> Read(IQuery<AssetManagement.Models.PowerPort> query)
		{
			if (_middleware is IReadableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnRead(query, _inner.Read);
			}
			else
			{
				return _inner.Read(query);
			}
		}

		public long Count(FilterElement<AssetManagement.Models.PowerPort> filter)
		{
			if (_middleware is ICountableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnCount(filter, _inner.Count);
			}
			else
			{
				return _inner.Count(filter);
			}
		}

		public long Count(IQuery<AssetManagement.Models.PowerPort> query)
		{
			if (_middleware is ICountableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnCount(query, _inner.Count);
			}
			else
			{
				return _inner.Count(query);
			}
		}

		public IReadOnlyCollection<AssetManagement.Models.PowerPort> Create(IEnumerable<AssetManagement.Models.PowerPort> oToCreate)
		{
			if (_middleware is IBulkCreatableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnCreate(oToCreate, _inner.Create);
			}
			else
			{
				return _inner.Create(oToCreate);
			}
		}

		public AssetManagement.Models.PowerPort Create(AssetManagement.Models.PowerPort oToCreate)
		{
			if (_middleware is ICreatableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnCreate(oToCreate, _inner.Create);
			}
			else
			{
				return _inner.Create(oToCreate);
			}
		}

		public IReadOnlyCollection<AssetManagement.Models.PowerPort> Update(IEnumerable<AssetManagement.Models.PowerPort> oToUpdate)
		{
			if (_middleware is IBulkUpdatableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnUpdate(oToUpdate, _inner.Update);
			}
			else
			{
				return _inner.Update(oToUpdate);
			}
		}

		public AssetManagement.Models.PowerPort Update(AssetManagement.Models.PowerPort oToUpdate)
		{
			if (_middleware is IUpdatableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				return middleware.OnUpdate(oToUpdate, _inner.Update);
			}
			else
			{
				return _inner.Update(oToUpdate);
			}
		}

		public void Delete(IEnumerable<AssetManagement.Models.PowerPort> oToDelete)
		{
			if (_middleware is IBulkDeletableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				middleware.OnDelete(oToDelete, _inner.Delete);
			}
			else
			{
				_inner.Delete(oToDelete);
			}
		}

		public void Delete(AssetManagement.Models.PowerPort oToDelete)
		{
			if (_middleware is IDeletableMiddleware<AssetManagement.Models.PowerPort> middleware)
			{
				middleware.OnDelete(oToDelete, _inner.Delete);
			}
			else
			{
				_inner.Delete(oToDelete);
			}
		}
		public System.Collections.Generic.IReadOnlyCollection<AssetManagement.Models.PowerPort> CreateOrUpdate(System.Collections.Generic.IEnumerable<AssetManagement.Models.PowerPort> oToCreateOrUpdate)
		{
                if (_middleware is IBulkRepositoryMiddleware<AssetManagement.Models.PowerPort> middleware)
                {
                    return middleware.OnCreateOrUpdate(oToCreateOrUpdate, _inner.CreateOrUpdate);
                }
                else
                {
                    return _inner.CreateOrUpdate(oToCreateOrUpdate);
                }
		}

	}
}