//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.PlanAndBuild.Models
{
    using System;

    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    [SdmDomMapper]
    internal static class PlanAndBuildAppSettingsDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.SlcPlan_And_Build.ModuleId;
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(SharedMappers.DomIds.SlcPlan_And_Build.Definitions.AppSettings.Id)
        { ModuleId = ModuleId };
        internal static class JobSettings
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobSettings.Id.Id)
            { ModuleId = ModuleId };

            internal static FieldDescriptorID JobIDPrefix = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobSettings.JobIDPrefix;
            internal static FieldDescriptorID JobIDNextSequence = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobSettings.JobIDNextSequence;
            internal static FieldDescriptorID JobIDIncrement = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobSettings.JobIDIncrement;
            internal static FieldDescriptorID JobIDStartingSeed = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobSettings.JobIDStartingSeed;
            internal static FieldDescriptorID JobIDMinimumDigits = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobSettings.JobIDMinimumDigits;
        }
    }
}
