//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
using Skyline.DataMiner.Net.Sections;
using Skyline.DataMiner.SDM;

namespace Skyline.DataMiner.SDM.PlanAndBuild.Models
{
    [SdmDomMapper]
    public static class PlanAndBuildJobDomMapper
    {
        internal const string ModuleId = SharedMappers.DomIds.SlcPlan_And_Build.ModuleId;
        private static readonly DomDefinitionId PlanAndBuildJobDomDefinitionId = new DomDefinitionId(SharedMappers.DomIds.SlcPlan_And_Build.Definitions.Job.Id)
        {
            ModuleId = ModuleId
        };
        internal static DomDefinitionId DomDefinitionId => PlanAndBuildJobDomDefinitionId;

        public static class PlanAndBuildJobProperties
        {
            private static readonly SectionDefinitionID sectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.Id.Id)
            {
                ModuleId = ModuleId
            };
            internal static SectionDefinitionID SectionDefinitionId => sectionDefinitionId;

            public static readonly FieldDescriptorID JobID = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.JobID;
            public static readonly FieldDescriptorID JobName = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.JobName;
            public static readonly FieldDescriptorID Start = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.Start;
            public static readonly FieldDescriptorID End = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.End;
            public static readonly FieldDescriptorID JobType = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.JobType;
            public static readonly FieldDescriptorID Type = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.Type;
            public static readonly FieldDescriptorID JobDescription = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.JobDescription;
            public static readonly FieldDescriptorID Remarks = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.Remarks;
            public static readonly FieldDescriptorID Priority = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.Priority;
            public static readonly FieldDescriptorID SubState = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.SubState;
            public static readonly FieldDescriptorID Locations = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobInformation.Locations;
        }

        public static class Ownership
        {
            private static readonly SectionDefinitionID sectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobOwnership.Id.Id)
            {
                ModuleId = ModuleId
            };
            internal static SectionDefinitionID SectionDefinitionId => sectionDefinitionId;

            public static readonly FieldDescriptorID AssignedTo = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobOwnership.AssignedTo;
            public static readonly FieldDescriptorID AssignmentGroup = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobOwnership.AssignmentGroup;
        }

        public static class AssetsUsed
        {
            private static readonly SectionDefinitionID sectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcPlan_And_Build.Sections.AssetsUsed.Id.Id)
            {
                ModuleId = ModuleId
            };
            internal static SectionDefinitionID SectionDefinitionId => sectionDefinitionId;

            public static readonly FieldDescriptorID AssetId = SharedMappers.DomIds.SlcPlan_And_Build.Sections.AssetsUsed.AssetID;
            public static readonly FieldDescriptorID Action = SharedMappers.DomIds.SlcPlan_And_Build.Sections.AssetsUsed.Action;
        }

        public static class Attachments
        {
            private static readonly SectionDefinitionID sectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobAttachment.Id.Id)
            {
                ModuleId = ModuleId
            };
            internal static SectionDefinitionID SectionDefinitionId => sectionDefinitionId;

            public static readonly FieldDescriptorID FilePath = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobAttachment.FilePath;
            public static readonly FieldDescriptorID AttachedAt = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobAttachment.AttachedAt;
            public static readonly FieldDescriptorID AttachedBy = SharedMappers.DomIds.SlcPlan_And_Build.Sections.JobAttachment.AttachedBy;
        }

        public static class ConnectionsOnJob
        {
            private static readonly SectionDefinitionID sectionDefinitionId = new SectionDefinitionID(SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.Id.Id)
            {
                ModuleId = ModuleId
            };
            internal static SectionDefinitionID SectionDefinitionId => sectionDefinitionId;

            public static readonly FieldDescriptorID ConnectionId = SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.ConnectionID;
            public static readonly FieldDescriptorID Source = SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.Source;
            public static readonly FieldDescriptorID Destination = SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.Destination;
            public static readonly FieldDescriptorID Status = SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.Status;
            public static readonly FieldDescriptorID CableType = SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.Cabletype;
            public static readonly FieldDescriptorID CableLength = SharedMappers.DomIds.SlcPlan_And_Build.Sections.ConnectionsOnJob.CableLength;
        }
    }
}