//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;
    using System.Runtime.CompilerServices;

    using SharedMappers.DomIds;

    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM.Exposers;

    public static partial class HistoryExposers
    {
        public static readonly Exposer<History, string> Identifier =
            new Exposer<History, string>(obj => obj.Identifier, "Identifier");

        static HistoryExposers()
        {
            RuntimeHelpers.RunClassConstructor(typeof(HistoryInfo).TypeHandle);
        }

        public static partial class HistoryInfo
        {
            public static readonly Exposer<History, string> Description =
                new Exposer<History, string>(obj => obj.HistoryInfo.Description, "HistoryInfo.Description");

            public static readonly Exposer<History, Guid> Job =
                new Exposer<History, Guid>(obj => obj.HistoryInfo.Job, "HistoryInfo.Job");

            public static readonly Exposer<History, string> ModifiedInstanceID =
                new Exposer<History, string>(obj => obj.HistoryInfo.ModifiedInstanceID, "HistoryInfo.ModifiedInstanceID");

            public static readonly Exposer<History, string> ModifiedInstanceDefinitionID =
                new Exposer<History, string>(obj => obj.HistoryInfo.ModifiedInstanceDefinitionID, "HistoryInfo.ModifiedInstanceDefinitionID");

            public static readonly Exposer<History, string> ExtraInfo =
                new Exposer<History, string>(obj => obj.HistoryInfo.ExtraInfo, "HistoryInfo.ExtraInfo");

            public static readonly Exposer<History, SlcAsset_Management.Enums.TypeOfHistoryEnum?> TypeOfHistory =
                new Exposer<History, SlcAsset_Management.Enums.TypeOfHistoryEnum?>(
                    obj => obj.HistoryInfo.TypeOfHistory,
                    "HistoryInfo.TypeOfHistory");
        }
    }
}
