//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.AssetManagement.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;

    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;

    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class PortTypeExposers
    {
        public static readonly Exposer<AssetManagement.Models.PortType, string> Identifier = new Exposer<AssetManagement.Models.PortType, string>((obj) => obj.Identifier, "Identifier");
        public static readonly Exposer<AssetManagement.Models.PortType, string> Name = new Exposer<AssetManagement.Models.PortType, string>((obj) => obj.Name, "Name");
        public static readonly Exposer<AssetManagement.Models.PortType, string> Description = new Exposer<AssetManagement.Models.PortType, string>((obj) => obj.Description, "Description");
        static PortTypeExposers()
        {
            RuntimeHelpers.RunClassConstructor(typeof(CategoryLinks).TypeHandle);
            RuntimeHelpers.RunClassConstructor(typeof(CableFKs).TypeHandle);
        }

        public static partial class CategoryLinks
        {
            public static readonly CollectionExposer<AssetManagement.Models.PortType, SharedMappers.DomIds.SlcAsset_Management.Enums.CategoriesEnum> Categories = new CollectionExposer<AssetManagement.Models.PortType, SharedMappers.DomIds.SlcAsset_Management.Enums.CategoriesEnum>((obj) => obj.CategoryLinks.Categories.Where(x => x != null), "CategoryLinks.Categories");
        }

        public static partial class CableFKs
        {
            public static readonly CollectionExposer<AssetManagement.Models.PortType, SdmObjectReference<AssetManagement.Models.CableType>> CableTypeFks = new CollectionExposer<AssetManagement.Models.PortType, SdmObjectReference<AssetManagement.Models.CableType>>((obj) => obj.CableFKs.CableTypeFks.Where(x => x != null), "CableFKs.CableTypeFks");
        }
    }
}