//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.FacilityManagement.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;

    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM;
    using Skyline.DataMiner.SDM.Exposers;

    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class RowExposers
    {
        public static readonly Exposer<FacilityManagement.Models.Row, string> Identifier = new Exposer<FacilityManagement.Models.Row, string>((obj) => obj.Identifier, "Identifier");
        static RowExposers()
        {
            RuntimeHelpers.RunClassConstructor(typeof(RowProperties).TypeHandle);
            RuntimeHelpers.RunClassConstructor(typeof(RoomFk).TypeHandle);
            RuntimeHelpers.RunClassConstructor(typeof(Resource).TypeHandle);
        }

        public static partial class RowProperties
        {
            public static readonly Exposer<FacilityManagement.Models.Row, string> Name = new Exposer<FacilityManagement.Models.Row, string>((obj) => obj.Name, "Name");
            public static readonly Exposer<FacilityManagement.Models.Row, string> Plan = new Exposer<FacilityManagement.Models.Row, string>((obj) => obj.Plan, "Plan");
            public static readonly Exposer<FacilityManagement.Models.Row, string> Description = new Exposer<FacilityManagement.Models.Row, string>((obj) => obj.Description, "Description");
            public static readonly Exposer<FacilityManagement.Models.Row, string> Label = new Exposer<FacilityManagement.Models.Row, string>((obj) => obj.Label, "Label");
            public static readonly Exposer<FacilityManagement.Models.Row, string> RowId = new Exposer<FacilityManagement.Models.Row, string>((obj) => obj.RowId, "RowProperties.RowId");
            public static readonly Exposer<FacilityManagement.Models.Row, double?> YPosition = new Exposer<FacilityManagement.Models.Row, double?>((obj) => obj.YPosition, "YPosition");
        }

        public static partial class RoomFk
        {
            public static readonly Exposer<FacilityManagement.Models.Row, SdmObjectReference<FacilityManagement.Models.Room>> Room = new Exposer<FacilityManagement.Models.Row, SdmObjectReference<FacilityManagement.Models.Room>>((obj) => obj.RoomFk.Room, "RoomFk.Room");
        }

        public static partial class Resource
        {
            public static readonly Exposer<FacilityManagement.Models.Row, System.Guid> ResourceId = new Exposer<FacilityManagement.Models.Row, System.Guid>((obj) => obj.Resource.ResourceId, "Resource.ResourceId");
        }
    }
}