//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyline.DataMiner.SDM.FacilityManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Skyline.DataMiner.Net;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Apps.Sections.Sections;
    using Skyline.DataMiner.Net.Helper;
    using Skyline.DataMiner.Net.ManagerStore;
    using Skyline.DataMiner.Net.Messages;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.Net.SubscriptionFilters;
    using Skyline.DataMiner.SDM;

    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    internal sealed partial class ZoneDomRepository_Middleware : IBulkRepository<FacilityManagement.Models.Zone>
    {
        private readonly IBulkRepository<FacilityManagement.Models.Zone> _inner;
        private readonly IMiddlewareMarker<FacilityManagement.Models.Zone> _middleware;

        public ZoneDomRepository_Middleware(IBulkRepository<FacilityManagement.Models.Zone> inner, IMiddlewareMarker<FacilityManagement.Models.Zone> middleware)
        {
            _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            _middleware = middleware;
        }

        public IEnumerable<IPagedResult<FacilityManagement.Models.Zone>> ReadPaged(FilterElement<FacilityManagement.Models.Zone> filter)
        {
            if (_middleware is IPageableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnReadPaged(filter, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter);
            }
        }

        public IEnumerable<IPagedResult<FacilityManagement.Models.Zone>> ReadPaged(IQuery<FacilityManagement.Models.Zone> query)
        {
            if (_middleware is IPageableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnReadPaged(query, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query);
            }
        }

        public IEnumerable<IPagedResult<FacilityManagement.Models.Zone>> ReadPaged(FilterElement<FacilityManagement.Models.Zone> filter, int pageSize)
        {
            if (_middleware is IPageableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnReadPaged(filter, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(filter, pageSize);
            }
        }

        public IEnumerable<IPagedResult<FacilityManagement.Models.Zone>> ReadPaged(IQuery<FacilityManagement.Models.Zone> query, int pageSize)
        {
            if (_middleware is IPageableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnReadPaged(query, pageSize, _inner.ReadPaged);
            }
            else
            {
                return _inner.ReadPaged(query, pageSize);
            }
        }

        public IEnumerable<FacilityManagement.Models.Zone> Read(FilterElement<FacilityManagement.Models.Zone> filter)
        {
            if (_middleware is IReadableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnRead(filter, _inner.Read);
            }
            else
            {
                return _inner.Read(filter);
            }
        }

        public IEnumerable<FacilityManagement.Models.Zone> Read(IQuery<FacilityManagement.Models.Zone> query)
        {
            if (_middleware is IReadableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnRead(query, _inner.Read);
            }
            else
            {
                return _inner.Read(query);
            }
        }

        public long Count(FilterElement<FacilityManagement.Models.Zone> filter)
        {
            if (_middleware is ICountableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnCount(filter, _inner.Count);
            }
            else
            {
                return _inner.Count(filter);
            }
        }

        public long Count(IQuery<FacilityManagement.Models.Zone> query)
        {
            if (_middleware is ICountableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnCount(query, _inner.Count);
            }
            else
            {
                return _inner.Count(query);
            }
        }

        public IReadOnlyCollection<FacilityManagement.Models.Zone> Create(IEnumerable<FacilityManagement.Models.Zone> oToCreate)
        {
            if (_middleware is IBulkCreatableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public FacilityManagement.Models.Zone Create(FacilityManagement.Models.Zone oToCreate)
        {
            if (_middleware is ICreatableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnCreate(oToCreate, _inner.Create);
            }
            else
            {
                return _inner.Create(oToCreate);
            }
        }

        public IReadOnlyCollection<FacilityManagement.Models.Zone> Update(IEnumerable<FacilityManagement.Models.Zone> oToUpdate)
        {
            if (_middleware is IBulkUpdatableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public FacilityManagement.Models.Zone Update(FacilityManagement.Models.Zone oToUpdate)
        {
            if (_middleware is IUpdatableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                return middleware.OnUpdate(oToUpdate, _inner.Update);
            }
            else
            {
                return _inner.Update(oToUpdate);
            }
        }

        public void Delete(IEnumerable<FacilityManagement.Models.Zone> oToDelete)
        {
            if (_middleware is IBulkDeletableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }

        public void Delete(FacilityManagement.Models.Zone oToDelete)
        {
            if (_middleware is IDeletableMiddleware<FacilityManagement.Models.Zone> middleware)
            {
                middleware.OnDelete(oToDelete, _inner.Delete);
            }
            else
            {
                _inner.Delete(oToDelete);
            }
        }
        public System.Collections.Generic.IReadOnlyCollection<FacilityManagement.Models.Zone> CreateOrUpdate(System.Collections.Generic.IEnumerable<FacilityManagement.Models.Zone> oToCreateOrUpdate)
        {
                if (_middleware is IBulkRepositoryMiddleware<FacilityManagement.Models.Zone> middleware)
                {
                    return middleware.OnCreateOrUpdate(oToCreateOrUpdate, _inner.CreateOrUpdate);
                }
                else
                {
                    return _inner.CreateOrUpdate(oToCreateOrUpdate);
                }
        }

    }
}
